// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_EDITORENVELOPE_NUBE_INTEROP_H_
#define FLATBUFFERS_GENERATED_EDITORENVELOPE_NUBE_INTEROP_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "usd_generated.h"

namespace NUBE {
namespace Interop {

struct EditorEnvelope;
struct EditorEnvelopeBuilder;

struct KillWorkerCommand;
struct KillWorkerCommandBuilder;

struct EngineStartupCommand;
struct EngineStartupCommandBuilder;

struct EngineShutdownCommand;
struct EngineShutdownCommandBuilder;

enum EditorMessage : uint8_t {
  EditorMessage_NONE = 0,
  EditorMessage_KillWorkerCommand = 1,
  EditorMessage_EngineStartupCommand = 2,
  EditorMessage_EngineShutdownCommand = 3,
  EditorMessage_USD_CreateStageCommand = 4,
  EditorMessage_USD_OpenStageCommand = 5,
  EditorMessage_USD_SaveStageCommand = 6,
  EditorMessage_USD_AddLayerCommand = 7,
  EditorMessage_USD_AddPrimCommand = 8,
  EditorMessage_USD_BakeStageCommand = 9,
  EditorMessage_MIN = EditorMessage_NONE,
  EditorMessage_MAX = EditorMessage_USD_BakeStageCommand
};

inline const EditorMessage (&EnumValuesEditorMessage())[10] {
  static const EditorMessage values[] = {
    EditorMessage_NONE,
    EditorMessage_KillWorkerCommand,
    EditorMessage_EngineStartupCommand,
    EditorMessage_EngineShutdownCommand,
    EditorMessage_USD_CreateStageCommand,
    EditorMessage_USD_OpenStageCommand,
    EditorMessage_USD_SaveStageCommand,
    EditorMessage_USD_AddLayerCommand,
    EditorMessage_USD_AddPrimCommand,
    EditorMessage_USD_BakeStageCommand
  };
  return values;
}

inline const char * const *EnumNamesEditorMessage() {
  static const char * const names[11] = {
    "NONE",
    "KillWorkerCommand",
    "EngineStartupCommand",
    "EngineShutdownCommand",
    "USD_CreateStageCommand",
    "USD_OpenStageCommand",
    "USD_SaveStageCommand",
    "USD_AddLayerCommand",
    "USD_AddPrimCommand",
    "USD_BakeStageCommand",
    nullptr
  };
  return names;
}

inline const char *EnumNameEditorMessage(EditorMessage e) {
  if (::flatbuffers::IsOutRange(e, EditorMessage_NONE, EditorMessage_USD_BakeStageCommand)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEditorMessage()[index];
}

template<typename T> struct EditorMessageTraits {
  static const EditorMessage enum_value = EditorMessage_NONE;
};

template<> struct EditorMessageTraits<NUBE::Interop::KillWorkerCommand> {
  static const EditorMessage enum_value = EditorMessage_KillWorkerCommand;
};

template<> struct EditorMessageTraits<NUBE::Interop::EngineStartupCommand> {
  static const EditorMessage enum_value = EditorMessage_EngineStartupCommand;
};

template<> struct EditorMessageTraits<NUBE::Interop::EngineShutdownCommand> {
  static const EditorMessage enum_value = EditorMessage_EngineShutdownCommand;
};

template<> struct EditorMessageTraits<NUBE::Interop::USD::CreateStageCommand> {
  static const EditorMessage enum_value = EditorMessage_USD_CreateStageCommand;
};

template<> struct EditorMessageTraits<NUBE::Interop::USD::OpenStageCommand> {
  static const EditorMessage enum_value = EditorMessage_USD_OpenStageCommand;
};

template<> struct EditorMessageTraits<NUBE::Interop::USD::SaveStageCommand> {
  static const EditorMessage enum_value = EditorMessage_USD_SaveStageCommand;
};

template<> struct EditorMessageTraits<NUBE::Interop::USD::AddLayerCommand> {
  static const EditorMessage enum_value = EditorMessage_USD_AddLayerCommand;
};

template<> struct EditorMessageTraits<NUBE::Interop::USD::AddPrimCommand> {
  static const EditorMessage enum_value = EditorMessage_USD_AddPrimCommand;
};

template<> struct EditorMessageTraits<NUBE::Interop::USD::BakeStageCommand> {
  static const EditorMessage enum_value = EditorMessage_USD_BakeStageCommand;
};

template <bool B = false>
bool VerifyEditorMessage(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, EditorMessage type);
template <bool B = false>
bool VerifyEditorMessageVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct EditorEnvelope FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EditorEnvelopeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  NUBE::Interop::EditorMessage payload_type() const {
    return static_cast<NUBE::Interop::EditorMessage>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const NUBE::Interop::KillWorkerCommand *payload_as_KillWorkerCommand() const {
    return payload_type() == NUBE::Interop::EditorMessage_KillWorkerCommand ? static_cast<const NUBE::Interop::KillWorkerCommand *>(payload()) : nullptr;
  }
  const NUBE::Interop::EngineStartupCommand *payload_as_EngineStartupCommand() const {
    return payload_type() == NUBE::Interop::EditorMessage_EngineStartupCommand ? static_cast<const NUBE::Interop::EngineStartupCommand *>(payload()) : nullptr;
  }
  const NUBE::Interop::EngineShutdownCommand *payload_as_EngineShutdownCommand() const {
    return payload_type() == NUBE::Interop::EditorMessage_EngineShutdownCommand ? static_cast<const NUBE::Interop::EngineShutdownCommand *>(payload()) : nullptr;
  }
  const NUBE::Interop::USD::CreateStageCommand *payload_as_USD_CreateStageCommand() const {
    return payload_type() == NUBE::Interop::EditorMessage_USD_CreateStageCommand ? static_cast<const NUBE::Interop::USD::CreateStageCommand *>(payload()) : nullptr;
  }
  const NUBE::Interop::USD::OpenStageCommand *payload_as_USD_OpenStageCommand() const {
    return payload_type() == NUBE::Interop::EditorMessage_USD_OpenStageCommand ? static_cast<const NUBE::Interop::USD::OpenStageCommand *>(payload()) : nullptr;
  }
  const NUBE::Interop::USD::SaveStageCommand *payload_as_USD_SaveStageCommand() const {
    return payload_type() == NUBE::Interop::EditorMessage_USD_SaveStageCommand ? static_cast<const NUBE::Interop::USD::SaveStageCommand *>(payload()) : nullptr;
  }
  const NUBE::Interop::USD::AddLayerCommand *payload_as_USD_AddLayerCommand() const {
    return payload_type() == NUBE::Interop::EditorMessage_USD_AddLayerCommand ? static_cast<const NUBE::Interop::USD::AddLayerCommand *>(payload()) : nullptr;
  }
  const NUBE::Interop::USD::AddPrimCommand *payload_as_USD_AddPrimCommand() const {
    return payload_type() == NUBE::Interop::EditorMessage_USD_AddPrimCommand ? static_cast<const NUBE::Interop::USD::AddPrimCommand *>(payload()) : nullptr;
  }
  const NUBE::Interop::USD::BakeStageCommand *payload_as_USD_BakeStageCommand() const {
    return payload_type() == NUBE::Interop::EditorMessage_USD_BakeStageCommand ? static_cast<const NUBE::Interop::USD::BakeStageCommand *>(payload()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyEditorMessage(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const NUBE::Interop::KillWorkerCommand *EditorEnvelope::payload_as<NUBE::Interop::KillWorkerCommand>() const {
  return payload_as_KillWorkerCommand();
}

template<> inline const NUBE::Interop::EngineStartupCommand *EditorEnvelope::payload_as<NUBE::Interop::EngineStartupCommand>() const {
  return payload_as_EngineStartupCommand();
}

template<> inline const NUBE::Interop::EngineShutdownCommand *EditorEnvelope::payload_as<NUBE::Interop::EngineShutdownCommand>() const {
  return payload_as_EngineShutdownCommand();
}

template<> inline const NUBE::Interop::USD::CreateStageCommand *EditorEnvelope::payload_as<NUBE::Interop::USD::CreateStageCommand>() const {
  return payload_as_USD_CreateStageCommand();
}

template<> inline const NUBE::Interop::USD::OpenStageCommand *EditorEnvelope::payload_as<NUBE::Interop::USD::OpenStageCommand>() const {
  return payload_as_USD_OpenStageCommand();
}

template<> inline const NUBE::Interop::USD::SaveStageCommand *EditorEnvelope::payload_as<NUBE::Interop::USD::SaveStageCommand>() const {
  return payload_as_USD_SaveStageCommand();
}

template<> inline const NUBE::Interop::USD::AddLayerCommand *EditorEnvelope::payload_as<NUBE::Interop::USD::AddLayerCommand>() const {
  return payload_as_USD_AddLayerCommand();
}

template<> inline const NUBE::Interop::USD::AddPrimCommand *EditorEnvelope::payload_as<NUBE::Interop::USD::AddPrimCommand>() const {
  return payload_as_USD_AddPrimCommand();
}

template<> inline const NUBE::Interop::USD::BakeStageCommand *EditorEnvelope::payload_as<NUBE::Interop::USD::BakeStageCommand>() const {
  return payload_as_USD_BakeStageCommand();
}

struct EditorEnvelopeBuilder {
  typedef EditorEnvelope Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(NUBE::Interop::EditorMessage payload_type) {
    fbb_.AddElement<uint8_t>(EditorEnvelope::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(EditorEnvelope::VT_PAYLOAD, payload);
  }
  explicit EditorEnvelopeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EditorEnvelope> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EditorEnvelope>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EditorEnvelope> CreateEditorEnvelope(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    NUBE::Interop::EditorMessage payload_type = NUBE::Interop::EditorMessage_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  EditorEnvelopeBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

struct KillWorkerCommand FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef KillWorkerCommandBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UNUSED = 4
  };
  bool unused() const {
    return GetField<uint8_t>(VT_UNUSED, 1) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_UNUSED, 1) &&
           verifier.EndTable();
  }
};

struct KillWorkerCommandBuilder {
  typedef KillWorkerCommand Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_unused(bool unused) {
    fbb_.AddElement<uint8_t>(KillWorkerCommand::VT_UNUSED, static_cast<uint8_t>(unused), 1);
  }
  explicit KillWorkerCommandBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<KillWorkerCommand> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<KillWorkerCommand>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<KillWorkerCommand> CreateKillWorkerCommand(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool unused = true) {
  KillWorkerCommandBuilder builder_(_fbb);
  builder_.add_unused(unused);
  return builder_.Finish();
}

struct EngineStartupCommand FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EngineStartupCommandBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UNUSED = 4
  };
  bool unused() const {
    return GetField<uint8_t>(VT_UNUSED, 1) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_UNUSED, 1) &&
           verifier.EndTable();
  }
};

struct EngineStartupCommandBuilder {
  typedef EngineStartupCommand Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_unused(bool unused) {
    fbb_.AddElement<uint8_t>(EngineStartupCommand::VT_UNUSED, static_cast<uint8_t>(unused), 1);
  }
  explicit EngineStartupCommandBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EngineStartupCommand> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EngineStartupCommand>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EngineStartupCommand> CreateEngineStartupCommand(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool unused = true) {
  EngineStartupCommandBuilder builder_(_fbb);
  builder_.add_unused(unused);
  return builder_.Finish();
}

struct EngineShutdownCommand FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EngineShutdownCommandBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UNUSED = 4
  };
  bool unused() const {
    return GetField<uint8_t>(VT_UNUSED, 1) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_UNUSED, 1) &&
           verifier.EndTable();
  }
};

struct EngineShutdownCommandBuilder {
  typedef EngineShutdownCommand Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_unused(bool unused) {
    fbb_.AddElement<uint8_t>(EngineShutdownCommand::VT_UNUSED, static_cast<uint8_t>(unused), 1);
  }
  explicit EngineShutdownCommandBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EngineShutdownCommand> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EngineShutdownCommand>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EngineShutdownCommand> CreateEngineShutdownCommand(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool unused = true) {
  EngineShutdownCommandBuilder builder_(_fbb);
  builder_.add_unused(unused);
  return builder_.Finish();
}

template <bool B>
inline bool VerifyEditorMessage(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, EditorMessage type) {
  switch (type) {
    case EditorMessage_NONE: {
      return true;
    }
    case EditorMessage_KillWorkerCommand: {
      auto ptr = reinterpret_cast<const NUBE::Interop::KillWorkerCommand *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EditorMessage_EngineStartupCommand: {
      auto ptr = reinterpret_cast<const NUBE::Interop::EngineStartupCommand *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EditorMessage_EngineShutdownCommand: {
      auto ptr = reinterpret_cast<const NUBE::Interop::EngineShutdownCommand *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EditorMessage_USD_CreateStageCommand: {
      auto ptr = reinterpret_cast<const NUBE::Interop::USD::CreateStageCommand *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EditorMessage_USD_OpenStageCommand: {
      auto ptr = reinterpret_cast<const NUBE::Interop::USD::OpenStageCommand *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EditorMessage_USD_SaveStageCommand: {
      auto ptr = reinterpret_cast<const NUBE::Interop::USD::SaveStageCommand *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EditorMessage_USD_AddLayerCommand: {
      auto ptr = reinterpret_cast<const NUBE::Interop::USD::AddLayerCommand *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EditorMessage_USD_AddPrimCommand: {
      auto ptr = reinterpret_cast<const NUBE::Interop::USD::AddPrimCommand *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EditorMessage_USD_BakeStageCommand: {
      auto ptr = reinterpret_cast<const NUBE::Interop::USD::BakeStageCommand *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyEditorMessageVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyEditorMessage(
        verifier,  values->Get(i), types->GetEnum<EditorMessage>(i))) {
      return false;
    }
  }
  return true;
}

inline const NUBE::Interop::EditorEnvelope *GetEditorEnvelope(const void *buf) {
  return ::flatbuffers::GetRoot<NUBE::Interop::EditorEnvelope>(buf);
}

inline const NUBE::Interop::EditorEnvelope *GetSizePrefixedEditorEnvelope(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<NUBE::Interop::EditorEnvelope>(buf);
}

template <bool B = false>
inline bool VerifyEditorEnvelopeBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<NUBE::Interop::EditorEnvelope>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedEditorEnvelopeBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<NUBE::Interop::EditorEnvelope>(nullptr);
}

inline void FinishEditorEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<NUBE::Interop::EditorEnvelope> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEditorEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<NUBE::Interop::EditorEnvelope> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Interop
}  // namespace NUBE

#endif  // FLATBUFFERS_GENERATED_EDITORENVELOPE_NUBE_INTEROP_H_
