// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENGINE_NUBE_INTEROP_H_
#define FLATBUFFERS_GENERATED_ENGINE_NUBE_INTEROP_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace NUBE {
namespace Interop {

struct RenderInfo;
struct RenderInfoBuilder;

struct RenderInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RenderInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MAX_FRAMES_IN_FLIGHT = 4,
    VT_TARGET_HANDLES = 6
  };
  int16_t max_frames_in_flight() const {
    return GetField<int16_t>(VT_MAX_FRAMES_IN_FLIGHT, 0);
  }
  const ::flatbuffers::Vector<uint64_t> *target_handles() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_TARGET_HANDLES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_MAX_FRAMES_IN_FLIGHT, 2) &&
           VerifyOffset(verifier, VT_TARGET_HANDLES) &&
           verifier.VerifyVector(target_handles()) &&
           verifier.EndTable();
  }
};

struct RenderInfoBuilder {
  typedef RenderInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_max_frames_in_flight(int16_t max_frames_in_flight) {
    fbb_.AddElement<int16_t>(RenderInfo::VT_MAX_FRAMES_IN_FLIGHT, max_frames_in_flight, 0);
  }
  void add_target_handles(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> target_handles) {
    fbb_.AddOffset(RenderInfo::VT_TARGET_HANDLES, target_handles);
  }
  explicit RenderInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RenderInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RenderInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RenderInfo> CreateRenderInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int16_t max_frames_in_flight = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> target_handles = 0) {
  RenderInfoBuilder builder_(_fbb);
  builder_.add_target_handles(target_handles);
  builder_.add_max_frames_in_flight(max_frames_in_flight);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RenderInfo> CreateRenderInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int16_t max_frames_in_flight = 0,
    const std::vector<uint64_t> *target_handles = nullptr) {
  auto target_handles__ = target_handles ? _fbb.CreateVector<uint64_t>(*target_handles) : 0;
  return NUBE::Interop::CreateRenderInfo(
      _fbb,
      max_frames_in_flight,
      target_handles__);
}

}  // namespace Interop
}  // namespace NUBE

#endif  // FLATBUFFERS_GENERATED_ENGINE_NUBE_INTEROP_H_
