// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENGINEENVELOPE_NUBE_INTEROP_H_
#define FLATBUFFERS_GENERATED_ENGINEENVELOPE_NUBE_INTEROP_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace NUBE {
namespace Interop {

struct EngineEnvelope;
struct EngineEnvelopeBuilder;

struct InitializationDetails;
struct InitializationDetailsBuilder;

enum EngineMessage : uint8_t {
  EngineMessage_NONE = 0,
  EngineMessage_InitializationDetails = 1,
  EngineMessage_MIN = EngineMessage_NONE,
  EngineMessage_MAX = EngineMessage_InitializationDetails
};

inline const EngineMessage (&EnumValuesEngineMessage())[2] {
  static const EngineMessage values[] = {
    EngineMessage_NONE,
    EngineMessage_InitializationDetails
  };
  return values;
}

inline const char * const *EnumNamesEngineMessage() {
  static const char * const names[3] = {
    "NONE",
    "InitializationDetails",
    nullptr
  };
  return names;
}

inline const char *EnumNameEngineMessage(EngineMessage e) {
  if (::flatbuffers::IsOutRange(e, EngineMessage_NONE, EngineMessage_InitializationDetails)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEngineMessage()[index];
}

template<typename T> struct EngineMessageTraits {
  static const EngineMessage enum_value = EngineMessage_NONE;
};

template<> struct EngineMessageTraits<NUBE::Interop::InitializationDetails> {
  static const EngineMessage enum_value = EngineMessage_InitializationDetails;
};

template <bool B = false>
bool VerifyEngineMessage(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, EngineMessage type);
template <bool B = false>
bool VerifyEngineMessageVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct EngineEnvelope FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EngineEnvelopeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  NUBE::Interop::EngineMessage payload_type() const {
    return static_cast<NUBE::Interop::EngineMessage>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const NUBE::Interop::InitializationDetails *payload_as_InitializationDetails() const {
    return payload_type() == NUBE::Interop::EngineMessage_InitializationDetails ? static_cast<const NUBE::Interop::InitializationDetails *>(payload()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyEngineMessage(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const NUBE::Interop::InitializationDetails *EngineEnvelope::payload_as<NUBE::Interop::InitializationDetails>() const {
  return payload_as_InitializationDetails();
}

struct EngineEnvelopeBuilder {
  typedef EngineEnvelope Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(NUBE::Interop::EngineMessage payload_type) {
    fbb_.AddElement<uint8_t>(EngineEnvelope::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(EngineEnvelope::VT_PAYLOAD, payload);
  }
  explicit EngineEnvelopeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EngineEnvelope> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EngineEnvelope>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EngineEnvelope> CreateEngineEnvelope(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    NUBE::Interop::EngineMessage payload_type = NUBE::Interop::EngineMessage_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  EngineEnvelopeBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

struct InitializationDetails FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef InitializationDetailsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MAX_FRAMES_IN_FLIGHT = 4,
    VT_TARGET_HANDLES = 6,
    VT_ENGINE_URL = 8
  };
  int16_t max_frames_in_flight() const {
    return GetField<int16_t>(VT_MAX_FRAMES_IN_FLIGHT, 0);
  }
  const ::flatbuffers::Vector<uint64_t> *target_handles() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_TARGET_HANDLES);
  }
  const ::flatbuffers::String *engine_url() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ENGINE_URL);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_MAX_FRAMES_IN_FLIGHT, 2) &&
           VerifyOffset(verifier, VT_TARGET_HANDLES) &&
           verifier.VerifyVector(target_handles()) &&
           VerifyOffset(verifier, VT_ENGINE_URL) &&
           verifier.VerifyString(engine_url()) &&
           verifier.EndTable();
  }
};

struct InitializationDetailsBuilder {
  typedef InitializationDetails Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_max_frames_in_flight(int16_t max_frames_in_flight) {
    fbb_.AddElement<int16_t>(InitializationDetails::VT_MAX_FRAMES_IN_FLIGHT, max_frames_in_flight, 0);
  }
  void add_target_handles(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> target_handles) {
    fbb_.AddOffset(InitializationDetails::VT_TARGET_HANDLES, target_handles);
  }
  void add_engine_url(::flatbuffers::Offset<::flatbuffers::String> engine_url) {
    fbb_.AddOffset(InitializationDetails::VT_ENGINE_URL, engine_url);
  }
  explicit InitializationDetailsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<InitializationDetails> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<InitializationDetails>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<InitializationDetails> CreateInitializationDetails(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int16_t max_frames_in_flight = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> target_handles = 0,
    ::flatbuffers::Offset<::flatbuffers::String> engine_url = 0) {
  InitializationDetailsBuilder builder_(_fbb);
  builder_.add_engine_url(engine_url);
  builder_.add_target_handles(target_handles);
  builder_.add_max_frames_in_flight(max_frames_in_flight);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<InitializationDetails> CreateInitializationDetailsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int16_t max_frames_in_flight = 0,
    const std::vector<uint64_t> *target_handles = nullptr,
    const char *engine_url = nullptr) {
  auto target_handles__ = target_handles ? _fbb.CreateVector<uint64_t>(*target_handles) : 0;
  auto engine_url__ = engine_url ? _fbb.CreateString(engine_url) : 0;
  return NUBE::Interop::CreateInitializationDetails(
      _fbb,
      max_frames_in_flight,
      target_handles__,
      engine_url__);
}

template <bool B>
inline bool VerifyEngineMessage(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, EngineMessage type) {
  switch (type) {
    case EngineMessage_NONE: {
      return true;
    }
    case EngineMessage_InitializationDetails: {
      auto ptr = reinterpret_cast<const NUBE::Interop::InitializationDetails *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyEngineMessageVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyEngineMessage(
        verifier,  values->Get(i), types->GetEnum<EngineMessage>(i))) {
      return false;
    }
  }
  return true;
}

inline const NUBE::Interop::EngineEnvelope *GetEngineEnvelope(const void *buf) {
  return ::flatbuffers::GetRoot<NUBE::Interop::EngineEnvelope>(buf);
}

inline const NUBE::Interop::EngineEnvelope *GetSizePrefixedEngineEnvelope(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<NUBE::Interop::EngineEnvelope>(buf);
}

template <bool B = false>
inline bool VerifyEngineEnvelopeBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<NUBE::Interop::EngineEnvelope>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedEngineEnvelopeBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<NUBE::Interop::EngineEnvelope>(nullptr);
}

inline void FinishEngineEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<NUBE::Interop::EngineEnvelope> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEngineEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<NUBE::Interop::EngineEnvelope> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Interop
}  // namespace NUBE

#endif  // FLATBUFFERS_GENERATED_ENGINEENVELOPE_NUBE_INTEROP_H_
