// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PIPEDENVELOPE_NUBE_INTEROP_PIPED_H_
#define FLATBUFFERS_GENERATED_PIPEDENVELOPE_NUBE_INTEROP_PIPED_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace NUBE {
namespace Interop {
namespace Piped {

struct PipedEnvelope;
struct PipedEnvelopeBuilder;

struct KeyboardEvent;
struct KeyboardEventBuilder;

struct MouseMoveEvent;
struct MouseMoveEventBuilder;

enum PipedMessage : uint8_t {
  PipedMessage_NONE = 0,
  PipedMessage_KeyboardEvent = 1,
  PipedMessage_MouseMoveEvent = 2,
  PipedMessage_MIN = PipedMessage_NONE,
  PipedMessage_MAX = PipedMessage_MouseMoveEvent
};

inline const PipedMessage (&EnumValuesPipedMessage())[3] {
  static const PipedMessage values[] = {
    PipedMessage_NONE,
    PipedMessage_KeyboardEvent,
    PipedMessage_MouseMoveEvent
  };
  return values;
}

inline const char * const *EnumNamesPipedMessage() {
  static const char * const names[4] = {
    "NONE",
    "KeyboardEvent",
    "MouseMoveEvent",
    nullptr
  };
  return names;
}

inline const char *EnumNamePipedMessage(PipedMessage e) {
  if (::flatbuffers::IsOutRange(e, PipedMessage_NONE, PipedMessage_MouseMoveEvent)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPipedMessage()[index];
}

template<typename T> struct PipedMessageTraits {
  static const PipedMessage enum_value = PipedMessage_NONE;
};

template<> struct PipedMessageTraits<NUBE::Interop::Piped::KeyboardEvent> {
  static const PipedMessage enum_value = PipedMessage_KeyboardEvent;
};

template<> struct PipedMessageTraits<NUBE::Interop::Piped::MouseMoveEvent> {
  static const PipedMessage enum_value = PipedMessage_MouseMoveEvent;
};

template <bool B = false>
bool VerifyPipedMessage(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, PipedMessage type);
template <bool B = false>
bool VerifyPipedMessageVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct PipedEnvelope FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PipedEnvelopeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  NUBE::Interop::Piped::PipedMessage payload_type() const {
    return static_cast<NUBE::Interop::Piped::PipedMessage>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const NUBE::Interop::Piped::KeyboardEvent *payload_as_KeyboardEvent() const {
    return payload_type() == NUBE::Interop::Piped::PipedMessage_KeyboardEvent ? static_cast<const NUBE::Interop::Piped::KeyboardEvent *>(payload()) : nullptr;
  }
  const NUBE::Interop::Piped::MouseMoveEvent *payload_as_MouseMoveEvent() const {
    return payload_type() == NUBE::Interop::Piped::PipedMessage_MouseMoveEvent ? static_cast<const NUBE::Interop::Piped::MouseMoveEvent *>(payload()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyPipedMessage(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const NUBE::Interop::Piped::KeyboardEvent *PipedEnvelope::payload_as<NUBE::Interop::Piped::KeyboardEvent>() const {
  return payload_as_KeyboardEvent();
}

template<> inline const NUBE::Interop::Piped::MouseMoveEvent *PipedEnvelope::payload_as<NUBE::Interop::Piped::MouseMoveEvent>() const {
  return payload_as_MouseMoveEvent();
}

struct PipedEnvelopeBuilder {
  typedef PipedEnvelope Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(NUBE::Interop::Piped::PipedMessage payload_type) {
    fbb_.AddElement<uint8_t>(PipedEnvelope::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(PipedEnvelope::VT_PAYLOAD, payload);
  }
  explicit PipedEnvelopeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PipedEnvelope> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PipedEnvelope>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PipedEnvelope> CreatePipedEnvelope(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    NUBE::Interop::Piped::PipedMessage payload_type = NUBE::Interop::Piped::PipedMessage_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  PipedEnvelopeBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

struct KeyboardEvent FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef KeyboardEventBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCANCODE = 4,
    VT_IS_DOWN = 6
  };
  uint16_t scancode() const {
    return GetField<uint16_t>(VT_SCANCODE, 0);
  }
  bool is_down() const {
    return GetField<uint8_t>(VT_IS_DOWN, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_SCANCODE, 2) &&
           VerifyField<uint8_t>(verifier, VT_IS_DOWN, 1) &&
           verifier.EndTable();
  }
};

struct KeyboardEventBuilder {
  typedef KeyboardEvent Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_scancode(uint16_t scancode) {
    fbb_.AddElement<uint16_t>(KeyboardEvent::VT_SCANCODE, scancode, 0);
  }
  void add_is_down(bool is_down) {
    fbb_.AddElement<uint8_t>(KeyboardEvent::VT_IS_DOWN, static_cast<uint8_t>(is_down), 0);
  }
  explicit KeyboardEventBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<KeyboardEvent> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<KeyboardEvent>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<KeyboardEvent> CreateKeyboardEvent(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t scancode = 0,
    bool is_down = false) {
  KeyboardEventBuilder builder_(_fbb);
  builder_.add_scancode(scancode);
  builder_.add_is_down(is_down);
  return builder_.Finish();
}

struct MouseMoveEvent FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MouseMoveEventBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_X_REL = 8,
    VT_Y_REL = 10
  };
  int32_t x() const {
    return GetField<int32_t>(VT_X, 0);
  }
  int32_t y() const {
    return GetField<int32_t>(VT_Y, 0);
  }
  int32_t x_rel() const {
    return GetField<int32_t>(VT_X_REL, 0);
  }
  int32_t y_rel() const {
    return GetField<int32_t>(VT_Y_REL, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_X, 4) &&
           VerifyField<int32_t>(verifier, VT_Y, 4) &&
           VerifyField<int32_t>(verifier, VT_X_REL, 4) &&
           VerifyField<int32_t>(verifier, VT_Y_REL, 4) &&
           verifier.EndTable();
  }
};

struct MouseMoveEventBuilder {
  typedef MouseMoveEvent Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(int32_t x) {
    fbb_.AddElement<int32_t>(MouseMoveEvent::VT_X, x, 0);
  }
  void add_y(int32_t y) {
    fbb_.AddElement<int32_t>(MouseMoveEvent::VT_Y, y, 0);
  }
  void add_x_rel(int32_t x_rel) {
    fbb_.AddElement<int32_t>(MouseMoveEvent::VT_X_REL, x_rel, 0);
  }
  void add_y_rel(int32_t y_rel) {
    fbb_.AddElement<int32_t>(MouseMoveEvent::VT_Y_REL, y_rel, 0);
  }
  explicit MouseMoveEventBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MouseMoveEvent> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MouseMoveEvent>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MouseMoveEvent> CreateMouseMoveEvent(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t x = 0,
    int32_t y = 0,
    int32_t x_rel = 0,
    int32_t y_rel = 0) {
  MouseMoveEventBuilder builder_(_fbb);
  builder_.add_y_rel(y_rel);
  builder_.add_x_rel(x_rel);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

template <bool B>
inline bool VerifyPipedMessage(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, PipedMessage type) {
  switch (type) {
    case PipedMessage_NONE: {
      return true;
    }
    case PipedMessage_KeyboardEvent: {
      auto ptr = reinterpret_cast<const NUBE::Interop::Piped::KeyboardEvent *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PipedMessage_MouseMoveEvent: {
      auto ptr = reinterpret_cast<const NUBE::Interop::Piped::MouseMoveEvent *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyPipedMessageVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPipedMessage(
        verifier,  values->Get(i), types->GetEnum<PipedMessage>(i))) {
      return false;
    }
  }
  return true;
}

inline const NUBE::Interop::Piped::PipedEnvelope *GetPipedEnvelope(const void *buf) {
  return ::flatbuffers::GetRoot<NUBE::Interop::Piped::PipedEnvelope>(buf);
}

inline const NUBE::Interop::Piped::PipedEnvelope *GetSizePrefixedPipedEnvelope(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<NUBE::Interop::Piped::PipedEnvelope>(buf);
}

template <bool B = false>
inline bool VerifyPipedEnvelopeBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<NUBE::Interop::Piped::PipedEnvelope>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedPipedEnvelopeBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<NUBE::Interop::Piped::PipedEnvelope>(nullptr);
}

inline void FinishPipedEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<NUBE::Interop::Piped::PipedEnvelope> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPipedEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<NUBE::Interop::Piped::PipedEnvelope> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Piped
}  // namespace Interop
}  // namespace NUBE

#endif  // FLATBUFFERS_GENERATED_PIPEDENVELOPE_NUBE_INTEROP_PIPED_H_
