// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_USD_NUBE_INTEROP_USD_H_
#define FLATBUFFERS_GENERATED_USD_NUBE_INTEROP_USD_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace NUBE {
namespace Interop {
namespace USD {

struct CreateStageCommand;
struct CreateStageCommandBuilder;

struct OpenStageCommand;
struct OpenStageCommandBuilder;

struct SaveStageCommand;
struct SaveStageCommandBuilder;

struct AddLayerCommand;
struct AddLayerCommandBuilder;

struct AddPrimCommand;
struct AddPrimCommandBuilder;

struct BakeStageCommand;
struct BakeStageCommandBuilder;

struct CreateStageCommand FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CreateStageCommandBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PATH = 4
  };
  const ::flatbuffers::String *path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PATH);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyString(path()) &&
           verifier.EndTable();
  }
};

struct CreateStageCommandBuilder {
  typedef CreateStageCommand Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_path(::flatbuffers::Offset<::flatbuffers::String> path) {
    fbb_.AddOffset(CreateStageCommand::VT_PATH, path);
  }
  explicit CreateStageCommandBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CreateStageCommand> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CreateStageCommand>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CreateStageCommand> CreateCreateStageCommand(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> path = 0) {
  CreateStageCommandBuilder builder_(_fbb);
  builder_.add_path(path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CreateStageCommand> CreateCreateStageCommandDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *path = nullptr) {
  auto path__ = path ? _fbb.CreateString(path) : 0;
  return NUBE::Interop::USD::CreateCreateStageCommand(
      _fbb,
      path__);
}

struct OpenStageCommand FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OpenStageCommandBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PATH = 4
  };
  const ::flatbuffers::String *path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PATH);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyString(path()) &&
           verifier.EndTable();
  }
};

struct OpenStageCommandBuilder {
  typedef OpenStageCommand Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_path(::flatbuffers::Offset<::flatbuffers::String> path) {
    fbb_.AddOffset(OpenStageCommand::VT_PATH, path);
  }
  explicit OpenStageCommandBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<OpenStageCommand> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<OpenStageCommand>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<OpenStageCommand> CreateOpenStageCommand(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> path = 0) {
  OpenStageCommandBuilder builder_(_fbb);
  builder_.add_path(path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<OpenStageCommand> CreateOpenStageCommandDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *path = nullptr) {
  auto path__ = path ? _fbb.CreateString(path) : 0;
  return NUBE::Interop::USD::CreateOpenStageCommand(
      _fbb,
      path__);
}

struct SaveStageCommand FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SaveStageCommandBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UNUSED = 4
  };
  bool unused() const {
    return GetField<uint8_t>(VT_UNUSED, 1) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_UNUSED, 1) &&
           verifier.EndTable();
  }
};

struct SaveStageCommandBuilder {
  typedef SaveStageCommand Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_unused(bool unused) {
    fbb_.AddElement<uint8_t>(SaveStageCommand::VT_UNUSED, static_cast<uint8_t>(unused), 1);
  }
  explicit SaveStageCommandBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SaveStageCommand> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SaveStageCommand>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SaveStageCommand> CreateSaveStageCommand(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool unused = true) {
  SaveStageCommandBuilder builder_(_fbb);
  builder_.add_unused(unused);
  return builder_.Finish();
}

struct AddLayerCommand FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AddLayerCommandBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PATH = 4
  };
  const ::flatbuffers::String *path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PATH);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyString(path()) &&
           verifier.EndTable();
  }
};

struct AddLayerCommandBuilder {
  typedef AddLayerCommand Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_path(::flatbuffers::Offset<::flatbuffers::String> path) {
    fbb_.AddOffset(AddLayerCommand::VT_PATH, path);
  }
  explicit AddLayerCommandBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AddLayerCommand> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AddLayerCommand>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AddLayerCommand> CreateAddLayerCommand(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> path = 0) {
  AddLayerCommandBuilder builder_(_fbb);
  builder_.add_path(path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AddLayerCommand> CreateAddLayerCommandDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *path = nullptr) {
  auto path__ = path ? _fbb.CreateString(path) : 0;
  return NUBE::Interop::USD::CreateAddLayerCommand(
      _fbb,
      path__);
}

struct AddPrimCommand FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AddPrimCommandBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PATH = 4,
    VT_TYPE = 6
  };
  const ::flatbuffers::String *path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PATH);
  }
  const ::flatbuffers::String *type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TYPE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyString(path()) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyString(type()) &&
           verifier.EndTable();
  }
};

struct AddPrimCommandBuilder {
  typedef AddPrimCommand Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_path(::flatbuffers::Offset<::flatbuffers::String> path) {
    fbb_.AddOffset(AddPrimCommand::VT_PATH, path);
  }
  void add_type(::flatbuffers::Offset<::flatbuffers::String> type) {
    fbb_.AddOffset(AddPrimCommand::VT_TYPE, type);
  }
  explicit AddPrimCommandBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AddPrimCommand> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AddPrimCommand>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AddPrimCommand> CreateAddPrimCommand(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> type = 0) {
  AddPrimCommandBuilder builder_(_fbb);
  builder_.add_type(type);
  builder_.add_path(path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AddPrimCommand> CreateAddPrimCommandDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *path = nullptr,
    const char *type = nullptr) {
  auto path__ = path ? _fbb.CreateString(path) : 0;
  auto type__ = type ? _fbb.CreateString(type) : 0;
  return NUBE::Interop::USD::CreateAddPrimCommand(
      _fbb,
      path__,
      type__);
}

struct BakeStageCommand FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BakeStageCommandBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UNUSED = 4
  };
  bool unused() const {
    return GetField<uint8_t>(VT_UNUSED, 1) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_UNUSED, 1) &&
           verifier.EndTable();
  }
};

struct BakeStageCommandBuilder {
  typedef BakeStageCommand Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_unused(bool unused) {
    fbb_.AddElement<uint8_t>(BakeStageCommand::VT_UNUSED, static_cast<uint8_t>(unused), 1);
  }
  explicit BakeStageCommandBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BakeStageCommand> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BakeStageCommand>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BakeStageCommand> CreateBakeStageCommand(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool unused = true) {
  BakeStageCommandBuilder builder_(_fbb);
  builder_.add_unused(unused);
  return builder_.Finish();
}

}  // namespace USD
}  // namespace Interop
}  // namespace NUBE

#endif  // FLATBUFFERS_GENERATED_USD_NUBE_INTEROP_USD_H_
