// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace NUBE.Interop
{

public enum EditorMessage : byte
{
  NONE = 0,
  InitializationDetails = 1,
};



static public class EditorMessageVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((EditorMessage)typeId)
    {
      case EditorMessage.InitializationDetails:
        result = NUBE.Interop.InitializationDetailsVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
