// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace NUBE.Interop
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EditorEnvelope : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static EditorEnvelope GetRootAsEditorEnvelope(ByteBuffer _bb) { return GetRootAsEditorEnvelope(_bb, new EditorEnvelope()); }
  public static EditorEnvelope GetRootAsEditorEnvelope(ByteBuffer _bb, EditorEnvelope obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EditorEnvelope __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public NUBE.Interop.EditorMessage PayloadType { get { int o = __p.__offset(4); return o != 0 ? (NUBE.Interop.EditorMessage)__p.bb.Get(o + __p.bb_pos) : NUBE.Interop.EditorMessage.NONE; } }
  public TTable? Payload<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public NUBE.Interop.InitializationDetails PayloadAsInitializationDetails() { return Payload<NUBE.Interop.InitializationDetails>().Value; }

  public static Offset<NUBE.Interop.EditorEnvelope> CreateEditorEnvelope(FlatBufferBuilder builder,
      NUBE.Interop.EditorMessage payload_type = NUBE.Interop.EditorMessage.NONE,
      int payloadOffset = 0) {
    builder.StartTable(2);
    EditorEnvelope.AddPayload(builder, payloadOffset);
    EditorEnvelope.AddPayloadType(builder, payload_type);
    return EditorEnvelope.EndEditorEnvelope(builder);
  }

  public static void StartEditorEnvelope(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPayloadType(FlatBufferBuilder builder, NUBE.Interop.EditorMessage payloadType) { builder.AddByte(0, (byte)payloadType, 0); }
  public static void AddPayload(FlatBufferBuilder builder, int payloadOffset) { builder.AddOffset(1, payloadOffset, 0); }
  public static Offset<NUBE.Interop.EditorEnvelope> EndEditorEnvelope(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<NUBE.Interop.EditorEnvelope>(o);
  }
}


static public class EditorEnvelopeVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PayloadType*/, 1 /*NUBE.Interop.EditorMessage*/, 1, false)
      && verifier.VerifyUnion(tablePos, 4, 6 /*Payload*/, NUBE.Interop.EditorMessageVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
