// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace NUBE.Interop
{

public enum EngineMessage : byte
{
  NONE = 0,
  KeyboardEvent = 1,
};



static public class EngineMessageVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((EngineMessage)typeId)
    {
      case EngineMessage.KeyboardEvent:
        result = NUBE.Interop.KeyboardEventVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
