// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace NUBE.Interop
{

public enum EngineMessage : byte
{
  NONE = 0,
  EngineStartupCommand = 1,
  EngineShutdownCommand = 2,
  KeyboardEvent = 3,
};



static public class EngineMessageVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((EngineMessage)typeId)
    {
      case EngineMessage.EngineStartupCommand:
        result = NUBE.Interop.EngineStartupCommandVerify.Verify(verifier, tablePos);
        break;
      case EngineMessage.EngineShutdownCommand:
        result = NUBE.Interop.EngineShutdownCommandVerify.Verify(verifier, tablePos);
        break;
      case EngineMessage.KeyboardEvent:
        result = NUBE.Interop.KeyboardEventVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
