// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace NUBE.Interop
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EngineEnvelope : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static EngineEnvelope GetRootAsEngineEnvelope(ByteBuffer _bb) { return GetRootAsEngineEnvelope(_bb, new EngineEnvelope()); }
  public static EngineEnvelope GetRootAsEngineEnvelope(ByteBuffer _bb, EngineEnvelope obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyEngineEnvelope(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, EngineEnvelopeVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EngineEnvelope __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public NUBE.Interop.EngineMessage PayloadType { get { int o = __p.__offset(4); return o != 0 ? (NUBE.Interop.EngineMessage)__p.bb.Get(o + __p.bb_pos) : NUBE.Interop.EngineMessage.NONE; } }
  public TTable? Payload<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public NUBE.Interop.KeyboardEvent PayloadAsKeyboardEvent() { return Payload<NUBE.Interop.KeyboardEvent>().Value; }

  public static Offset<NUBE.Interop.EngineEnvelope> CreateEngineEnvelope(FlatBufferBuilder builder,
      NUBE.Interop.EngineMessage payload_type = NUBE.Interop.EngineMessage.NONE,
      int payloadOffset = 0) {
    builder.StartTable(2);
    EngineEnvelope.AddPayload(builder, payloadOffset);
    EngineEnvelope.AddPayloadType(builder, payload_type);
    return EngineEnvelope.EndEngineEnvelope(builder);
  }

  public static void StartEngineEnvelope(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPayloadType(FlatBufferBuilder builder, NUBE.Interop.EngineMessage payloadType) { builder.AddByte(0, (byte)payloadType, 0); }
  public static void AddPayload(FlatBufferBuilder builder, int payloadOffset) { builder.AddOffset(1, payloadOffset, 0); }
  public static Offset<NUBE.Interop.EngineEnvelope> EndEngineEnvelope(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<NUBE.Interop.EngineEnvelope>(o);
  }
  public static void FinishEngineEnvelopeBuffer(FlatBufferBuilder builder, Offset<NUBE.Interop.EngineEnvelope> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedEngineEnvelopeBuffer(FlatBufferBuilder builder, Offset<NUBE.Interop.EngineEnvelope> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class EngineEnvelopeVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PayloadType*/, 1 /*NUBE.Interop.EngineMessage*/, 1, false)
      && verifier.VerifyUnion(tablePos, 4, 6 /*Payload*/, NUBE.Interop.EngineMessageVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
