// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace NUBE.Interop
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EngineStartupCommand : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static EngineStartupCommand GetRootAsEngineStartupCommand(ByteBuffer _bb) { return GetRootAsEngineStartupCommand(_bb, new EngineStartupCommand()); }
  public static EngineStartupCommand GetRootAsEngineStartupCommand(ByteBuffer _bb, EngineStartupCommand obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EngineStartupCommand __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Unused { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)true; } }

  public static Offset<NUBE.Interop.EngineStartupCommand> CreateEngineStartupCommand(FlatBufferBuilder builder,
      bool unused = true) {
    builder.StartTable(1);
    EngineStartupCommand.AddUnused(builder, unused);
    return EngineStartupCommand.EndEngineStartupCommand(builder);
  }

  public static void StartEngineStartupCommand(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddUnused(FlatBufferBuilder builder, bool unused) { builder.AddBool(0, unused, true); }
  public static Offset<NUBE.Interop.EngineStartupCommand> EndEngineStartupCommand(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<NUBE.Interop.EngineStartupCommand>(o);
  }
}


static public class EngineStartupCommandVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Unused*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
