// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace NUBE.Interop
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct KeyboardEvent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static KeyboardEvent GetRootAsKeyboardEvent(ByteBuffer _bb) { return GetRootAsKeyboardEvent(_bb, new KeyboardEvent()); }
  public static KeyboardEvent GetRootAsKeyboardEvent(ByteBuffer _bb, KeyboardEvent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public KeyboardEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort Scancode { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public bool IsDown { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<NUBE.Interop.KeyboardEvent> CreateKeyboardEvent(FlatBufferBuilder builder,
      ushort scancode = 0,
      bool is_down = false) {
    builder.StartTable(2);
    KeyboardEvent.AddScancode(builder, scancode);
    KeyboardEvent.AddIsDown(builder, is_down);
    return KeyboardEvent.EndKeyboardEvent(builder);
  }

  public static void StartKeyboardEvent(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddScancode(FlatBufferBuilder builder, ushort scancode) { builder.AddUshort(0, scancode, 0); }
  public static void AddIsDown(FlatBufferBuilder builder, bool isDown) { builder.AddBool(1, isDown, false); }
  public static Offset<NUBE.Interop.KeyboardEvent> EndKeyboardEvent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<NUBE.Interop.KeyboardEvent>(o);
  }
}


static public class KeyboardEventVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Scancode*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 6 /*IsDown*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
