// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace NUBE.Interop
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct RenderInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static RenderInfo GetRootAsRenderInfo(ByteBuffer _bb) { return GetRootAsRenderInfo(_bb, new RenderInfo()); }
  public static RenderInfo GetRootAsRenderInfo(ByteBuffer _bb, RenderInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RenderInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short MaxFramesInFlight { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }
  public ulong TextureByteSize { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong TargetHandle1 { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong TargetHandle2 { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong TargetHandle3 { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<NUBE.Interop.RenderInfo> CreateRenderInfo(FlatBufferBuilder builder,
      short max_frames_in_flight = 0,
      ulong texture_byte_size = 0,
      ulong target_handle_1 = 0,
      ulong target_handle_2 = 0,
      ulong target_handle_3 = 0) {
    builder.StartTable(5);
    RenderInfo.AddTargetHandle3(builder, target_handle_3);
    RenderInfo.AddTargetHandle2(builder, target_handle_2);
    RenderInfo.AddTargetHandle1(builder, target_handle_1);
    RenderInfo.AddTextureByteSize(builder, texture_byte_size);
    RenderInfo.AddMaxFramesInFlight(builder, max_frames_in_flight);
    return RenderInfo.EndRenderInfo(builder);
  }

  public static void StartRenderInfo(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddMaxFramesInFlight(FlatBufferBuilder builder, short maxFramesInFlight) { builder.AddShort(0, maxFramesInFlight, 0); }
  public static void AddTextureByteSize(FlatBufferBuilder builder, ulong textureByteSize) { builder.AddUlong(1, textureByteSize, 0); }
  public static void AddTargetHandle1(FlatBufferBuilder builder, ulong targetHandle1) { builder.AddUlong(2, targetHandle1, 0); }
  public static void AddTargetHandle2(FlatBufferBuilder builder, ulong targetHandle2) { builder.AddUlong(3, targetHandle2, 0); }
  public static void AddTargetHandle3(FlatBufferBuilder builder, ulong targetHandle3) { builder.AddUlong(4, targetHandle3, 0); }
  public static Offset<NUBE.Interop.RenderInfo> EndRenderInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<NUBE.Interop.RenderInfo>(o);
  }
}


static public class RenderInfoVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*MaxFramesInFlight*/, 2 /*short*/, 2, false)
      && verifier.VerifyField(tablePos, 6 /*TextureByteSize*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*TargetHandle1*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 10 /*TargetHandle2*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 12 /*TargetHandle3*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
