// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace NUBE.Interop
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ShutdownEngineEvent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static ShutdownEngineEvent GetRootAsShutdownEngineEvent(ByteBuffer _bb) { return GetRootAsShutdownEngineEvent(_bb, new ShutdownEngineEvent()); }
  public static ShutdownEngineEvent GetRootAsShutdownEngineEvent(ByteBuffer _bb, ShutdownEngineEvent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ShutdownEngineEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartShutdownEngineEvent(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<NUBE.Interop.ShutdownEngineEvent> EndShutdownEngineEvent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<NUBE.Interop.ShutdownEngineEvent>(o);
  }
}


static public class ShutdownEngineEventVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
