edition = "2023";

package NUBE;

option csharp_namespace = "AvaloniaEditor.Proto.NUBE";

message EditorEnvelope {
    oneof payload {
	EngineStartupCommand startup = 1;
	EngineShutdownCommand shutdown = 2;
	KeyboardEvent keyboardEvent = 3;
	MouseMoveEvent mouseMoveEvent = 4;
	BakeStageCommand bakeStage = 5;
	LoadMeshCommand loadMesh = 6;
	CreateNodeCommand createNode = 7;
	AttachMeshCommand attachMesh = 8;
    }
}
message EngineStartupCommand {
    uint32 width = 1;
    uint32 height = 2;
}

message EngineShutdownCommand {}

message KeyboardEvent {
    uint32 scancode = 1;
    bool isDown = 2;
}

message MouseMoveEvent {
    int32 x = 1;
    int32 y = 2;
    int32 xRel = 3;
    int32 yRel = 4;
}

message BakeStageCommand {
    string usdPath = 1;
}

message LoadMeshCommand {
    string assetId = 1;
    string meshPath = 2;
}

message CreateNodeCommand {
    NodeHandle parent = 1;
}

message NodeHandle {
    uint64 index = 1;
    uint32 generation = 2;
}

message AttachMeshCommand {
    string assetId = 1;
    NodeHandle targetNode = 2;
}

message EngineEnvelope {
    oneof payload {
	InitializationDetails initDetails = 1;
	NodeHandle nodeHandle = 2;
    }
}

message InitializationDetails {
    uint32 maxFramesInFlight = 1;
    repeated uint64 targetHandles = 2;
    string engineUrl = 3;
}
