// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nube.proto
// Protobuf C++ Version: 7.34.1

#include "nube.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace NUBE {

inline constexpr MouseMoveEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        x_{0},
        y_{0},
        xrel_{0},
        yrel_{0} {}

template <typename>
constexpr MouseMoveEvent::MouseMoveEvent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(MouseMoveEvent_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct MouseMoveEventDefaultTypeInternal {
  constexpr MouseMoveEventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MouseMoveEventDefaultTypeInternal() {}
  union {
    MouseMoveEvent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MouseMoveEventDefaultTypeInternal _MouseMoveEvent_default_instance_;

inline constexpr KeyboardEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        scancode_{0u},
        isdown_{false} {}

template <typename>
constexpr KeyboardEvent::KeyboardEvent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(KeyboardEvent_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct KeyboardEventDefaultTypeInternal {
  constexpr KeyboardEventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~KeyboardEventDefaultTypeInternal() {}
  union {
    KeyboardEvent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 KeyboardEventDefaultTypeInternal _KeyboardEvent_default_instance_;

inline constexpr EngineStartupCommanad::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        width_{0u},
        height_{0u} {}

template <typename>
constexpr EngineStartupCommanad::EngineStartupCommanad(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(EngineStartupCommanad_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct EngineStartupCommanadDefaultTypeInternal {
  constexpr EngineStartupCommanadDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EngineStartupCommanadDefaultTypeInternal() {}
  union {
    EngineStartupCommanad _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EngineStartupCommanadDefaultTypeInternal _EngineStartupCommanad_default_instance_;

inline constexpr EditorEnvelope::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
constexpr EditorEnvelope::EditorEnvelope(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(EditorEnvelope_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct EditorEnvelopeDefaultTypeInternal {
  constexpr EditorEnvelopeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EditorEnvelopeDefaultTypeInternal() {}
  union {
    EditorEnvelope _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EditorEnvelopeDefaultTypeInternal _EditorEnvelope_default_instance_;
}  // namespace NUBE
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_nube_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_nube_2eproto = nullptr;
const ::uint32_t
    TableStruct_nube_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x004, // bitmap
        PROTOBUF_FIELD_OFFSET(::NUBE::EditorEnvelope, _impl_._oneof_case_[0]),
        PROTOBUF_FIELD_OFFSET(::NUBE::EditorEnvelope, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::NUBE::EditorEnvelope, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::NUBE::EditorEnvelope, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::NUBE::EditorEnvelope, _impl_.payload_),
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::NUBE::EngineStartupCommanad, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::NUBE::EngineStartupCommanad, _impl_.width_),
        PROTOBUF_FIELD_OFFSET(::NUBE::EngineStartupCommanad, _impl_.height_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::NUBE::KeyboardEvent, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::NUBE::KeyboardEvent, _impl_.scancode_),
        PROTOBUF_FIELD_OFFSET(::NUBE::KeyboardEvent, _impl_.isdown_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::NUBE::MouseMoveEvent, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::NUBE::MouseMoveEvent, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::NUBE::MouseMoveEvent, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::NUBE::MouseMoveEvent, _impl_.xrel_),
        PROTOBUF_FIELD_OFFSET(::NUBE::MouseMoveEvent, _impl_.yrel_),
        0,
        1,
        2,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::NUBE::EditorEnvelope)},
        {6, sizeof(::NUBE::EngineStartupCommanad)},
        {13, sizeof(::NUBE::KeyboardEvent)},
        {20, sizeof(::NUBE::MouseMoveEvent)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::NUBE::_EditorEnvelope_default_instance_._instance,
    &::NUBE::_EngineStartupCommanad_default_instance_._instance,
    &::NUBE::_KeyboardEvent_default_instance_._instance,
    &::NUBE::_MouseMoveEvent_default_instance_._instance,
};
const char descriptor_table_protodef_nube_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\nnube.proto\022\004NUBE\"\251\001\n\016EditorEnvelope\022.\n"
    "\007startup\030\001 \001(\0132\033.NUBE.EngineStartupComma"
    "nadH\000\022,\n\rkeyboardEvent\030\002 \001(\0132\023.NUBE.Keyb"
    "oardEventH\000\022.\n\016mouseMoveEvent\030\003 \001(\0132\024.NU"
    "BE.MouseMoveEventH\000B\t\n\007payload\"6\n\025Engine"
    "StartupCommanad\022\r\n\005width\030\001 \001(\r\022\016\n\006height"
    "\030\002 \001(\r\"1\n\rKeyboardEvent\022\020\n\010scancode\030\001 \001("
    "\r\022\016\n\006isDown\030\002 \001(\010\"B\n\016MouseMoveEvent\022\t\n\001x"
    "\030\001 \001(\005\022\t\n\001y\030\002 \001(\005\022\014\n\004xRel\030\003 \001(\005\022\014\n\004yRel\030"
    "\004 \001(\005B\034\252\002\031AvaloniaEditor.Proto.NUBEb\010edi"
    "tionsp\350\007"
};
static ::absl::once_flag descriptor_table_nube_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_nube_2eproto = {
    false,
    false,
    408,
    descriptor_table_protodef_nube_2eproto,
    "nube.proto",
    &descriptor_table_nube_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_nube_2eproto::offsets,
    file_level_enum_descriptors_nube_2eproto,
    file_level_service_descriptors_nube_2eproto,
};
namespace NUBE {
// ===================================================================

class EditorEnvelope::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::NUBE::EditorEnvelope, _impl_._oneof_case_);
};

void EditorEnvelope::set_allocated_startup(::NUBE::EngineStartupCommanad* PROTOBUF_NULLABLE startup) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (startup) {
    ::google::protobuf::Arena* submessage_arena = startup->GetArena();
    if (message_arena != submessage_arena) {
      startup = ::google::protobuf::internal::GetOwnedMessage(message_arena, startup, submessage_arena);
    }
    set_has_startup();
    _impl_.payload_.startup_ = startup;
  }
  // @@protoc_insertion_point(field_set_allocated:NUBE.EditorEnvelope.startup)
}
void EditorEnvelope::set_allocated_keyboardevent(::NUBE::KeyboardEvent* PROTOBUF_NULLABLE keyboardevent) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (keyboardevent) {
    ::google::protobuf::Arena* submessage_arena = keyboardevent->GetArena();
    if (message_arena != submessage_arena) {
      keyboardevent = ::google::protobuf::internal::GetOwnedMessage(message_arena, keyboardevent, submessage_arena);
    }
    set_has_keyboardevent();
    _impl_.payload_.keyboardevent_ = keyboardevent;
  }
  // @@protoc_insertion_point(field_set_allocated:NUBE.EditorEnvelope.keyboardEvent)
}
void EditorEnvelope::set_allocated_mousemoveevent(::NUBE::MouseMoveEvent* PROTOBUF_NULLABLE mousemoveevent) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (mousemoveevent) {
    ::google::protobuf::Arena* submessage_arena = mousemoveevent->GetArena();
    if (message_arena != submessage_arena) {
      mousemoveevent = ::google::protobuf::internal::GetOwnedMessage(message_arena, mousemoveevent, submessage_arena);
    }
    set_has_mousemoveevent();
    _impl_.payload_.mousemoveevent_ = mousemoveevent;
  }
  // @@protoc_insertion_point(field_set_allocated:NUBE.EditorEnvelope.mouseMoveEvent)
}
EditorEnvelope::EditorEnvelope(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EditorEnvelope_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NUBE.EditorEnvelope)
}
PROTOBUF_NDEBUG_INLINE EditorEnvelope::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::NUBE::EditorEnvelope& from_msg)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

EditorEnvelope::EditorEnvelope(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const EditorEnvelope& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EditorEnvelope_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EditorEnvelope* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (payload_case()) {
    case PAYLOAD_NOT_SET:
      break;
      case kStartup:
        _impl_.payload_.startup_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.startup_);
        break;
      case kKeyboardEvent:
        _impl_.payload_.keyboardevent_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.keyboardevent_);
        break;
      case kMouseMoveEvent:
        _impl_.payload_.mousemoveevent_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.mousemoveevent_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:NUBE.EditorEnvelope)
}
PROTOBUF_NDEBUG_INLINE EditorEnvelope::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void EditorEnvelope::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
EditorEnvelope::~EditorEnvelope() {
  // @@protoc_insertion_point(destructor:NUBE.EditorEnvelope)
  SharedDtor(*this);
}
inline void EditorEnvelope::SharedDtor(MessageLite& self) {
  EditorEnvelope& this_ = static_cast<EditorEnvelope&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_payload()) {
    this_.clear_payload();
  }
  this_._impl_.~Impl_();
}

void EditorEnvelope::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:NUBE.EditorEnvelope)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (payload_case()) {
    case kStartup: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.startup_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.startup_);
      }
      break;
    }
    case kKeyboardEvent: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.keyboardevent_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.keyboardevent_);
      }
      break;
    }
    case kMouseMoveEvent: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.mousemoveevent_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.mousemoveevent_);
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


inline void* PROTOBUF_NONNULL EditorEnvelope::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) EditorEnvelope(arena);
}
constexpr auto EditorEnvelope::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(EditorEnvelope),
                                            alignof(EditorEnvelope));
}
constexpr auto EditorEnvelope::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_EditorEnvelope_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &EditorEnvelope::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<EditorEnvelope>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &EditorEnvelope::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<EditorEnvelope>(), &EditorEnvelope::ByteSizeLong,
              &EditorEnvelope::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(EditorEnvelope, _impl_._cached_size_),
          false,
      },
      &EditorEnvelope::kDescriptorMethods,
      &descriptor_table_nube_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull EditorEnvelope_class_data_ =
        EditorEnvelope::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
EditorEnvelope::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&EditorEnvelope_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(EditorEnvelope_class_data_.tc_table);
  return EditorEnvelope_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 3, 3, 0, 2>
EditorEnvelope::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(EditorEnvelope,
                          _impl_._cached_size_),  // no hasbits
    0, // no _extensions_
    3, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    EditorEnvelope_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NUBE::EditorEnvelope>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .NUBE.EngineStartupCommanad startup = 1;
    {PROTOBUF_FIELD_OFFSET(EditorEnvelope, _impl_.payload_.startup_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .NUBE.KeyboardEvent keyboardEvent = 2;
    {PROTOBUF_FIELD_OFFSET(EditorEnvelope, _impl_.payload_.keyboardevent_), _Internal::kOneofCaseOffset + 0, 1, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .NUBE.MouseMoveEvent mouseMoveEvent = 3;
    {PROTOBUF_FIELD_OFFSET(EditorEnvelope, _impl_.payload_.mousemoveevent_), _Internal::kOneofCaseOffset + 0, 2, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::NUBE::EngineStartupCommanad>()},
      {::_pbi::TcParser::GetTable<::NUBE::KeyboardEvent>()},
      {::_pbi::TcParser::GetTable<::NUBE::MouseMoveEvent>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void EditorEnvelope::Clear() {
// @@protoc_insertion_point(message_clear_start:NUBE.EditorEnvelope)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_payload();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL EditorEnvelope::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const EditorEnvelope& this_ = static_cast<const EditorEnvelope&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL EditorEnvelope::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const EditorEnvelope& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:NUBE.EditorEnvelope)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (this_.payload_case()) {
    case kStartup: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          1, *this_._impl_.payload_.startup_, this_._impl_.payload_.startup_->GetCachedSize(), target,
          stream);
      break;
    }
    case kKeyboardEvent: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, *this_._impl_.payload_.keyboardevent_, this_._impl_.payload_.keyboardevent_->GetCachedSize(), target,
          stream);
      break;
    }
    case kMouseMoveEvent: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, *this_._impl_.payload_.mousemoveevent_, this_._impl_.payload_.mousemoveevent_->GetCachedSize(), target,
          stream);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NUBE.EditorEnvelope)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t EditorEnvelope::ByteSizeLong(const MessageLite& base) {
  const EditorEnvelope& this_ = static_cast<const EditorEnvelope&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t EditorEnvelope::ByteSizeLong() const {
  const EditorEnvelope& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:NUBE.EditorEnvelope)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  switch (this_.payload_case()) {
    // .NUBE.EngineStartupCommanad startup = 1;
    case kStartup: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.startup_);
      break;
    }
    // .NUBE.KeyboardEvent keyboardEvent = 2;
    case kKeyboardEvent: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.keyboardevent_);
      break;
    }
    // .NUBE.MouseMoveEvent mouseMoveEvent = 3;
    case kMouseMoveEvent: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.mousemoveevent_);
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void EditorEnvelope::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<EditorEnvelope*>(&to_msg);
  auto& from = static_cast<const EditorEnvelope&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:NUBE.EditorEnvelope)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  if (const uint32_t oneof_from_case =
          from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_payload();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kStartup: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.startup_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.startup_);
        } else {
          _this->_impl_.payload_.startup_->MergeFrom(*from._impl_.payload_.startup_);
        }
        break;
      }
      case kKeyboardEvent: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.keyboardevent_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.keyboardevent_);
        } else {
          _this->_impl_.payload_.keyboardevent_->MergeFrom(*from._impl_.payload_.keyboardevent_);
        }
        break;
      }
      case kMouseMoveEvent: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.mousemoveevent_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.mousemoveevent_);
        } else {
          _this->_impl_.payload_.mousemoveevent_->MergeFrom(*from._impl_.payload_.mousemoveevent_);
        }
        break;
      }
      case PAYLOAD_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void EditorEnvelope::CopyFrom(const EditorEnvelope& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:NUBE.EditorEnvelope)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EditorEnvelope::InternalSwap(EditorEnvelope* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata EditorEnvelope::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EngineStartupCommanad::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<EngineStartupCommanad>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(EngineStartupCommanad, _impl_._has_bits_);
};

EngineStartupCommanad::EngineStartupCommanad(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EngineStartupCommanad_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NUBE.EngineStartupCommanad)
}
EngineStartupCommanad::EngineStartupCommanad(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const EngineStartupCommanad& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EngineStartupCommanad_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE EngineStartupCommanad::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void EngineStartupCommanad::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, width_),
           0,
           offsetof(Impl_, height_) -
               offsetof(Impl_, width_) +
               sizeof(Impl_::height_));
}
EngineStartupCommanad::~EngineStartupCommanad() {
  // @@protoc_insertion_point(destructor:NUBE.EngineStartupCommanad)
  SharedDtor(*this);
}
inline void EngineStartupCommanad::SharedDtor(MessageLite& self) {
  EngineStartupCommanad& this_ = static_cast<EngineStartupCommanad&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL EngineStartupCommanad::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) EngineStartupCommanad(arena);
}
constexpr auto EngineStartupCommanad::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(EngineStartupCommanad),
                                            alignof(EngineStartupCommanad));
}
constexpr auto EngineStartupCommanad::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_EngineStartupCommanad_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &EngineStartupCommanad::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<EngineStartupCommanad>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &EngineStartupCommanad::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<EngineStartupCommanad>(), &EngineStartupCommanad::ByteSizeLong,
              &EngineStartupCommanad::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(EngineStartupCommanad, _impl_._cached_size_),
          false,
      },
      &EngineStartupCommanad::kDescriptorMethods,
      &descriptor_table_nube_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull EngineStartupCommanad_class_data_ =
        EngineStartupCommanad::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
EngineStartupCommanad::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&EngineStartupCommanad_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(EngineStartupCommanad_class_data_.tc_table);
  return EngineStartupCommanad_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
EngineStartupCommanad::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(EngineStartupCommanad, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    EngineStartupCommanad_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NUBE::EngineStartupCommanad>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 height = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(EngineStartupCommanad, _impl_.height_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(EngineStartupCommanad, _impl_.height_)}},
    // uint32 width = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(EngineStartupCommanad, _impl_.width_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(EngineStartupCommanad, _impl_.width_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 width = 1;
    {PROTOBUF_FIELD_OFFSET(EngineStartupCommanad, _impl_.width_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 height = 2;
    {PROTOBUF_FIELD_OFFSET(EngineStartupCommanad, _impl_.height_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void EngineStartupCommanad::Clear() {
// @@protoc_insertion_point(message_clear_start:NUBE.EngineStartupCommanad)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    ::memset(&_impl_.width_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.height_) -
        reinterpret_cast<char*>(&_impl_.width_)) + sizeof(_impl_.height_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL EngineStartupCommanad::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const EngineStartupCommanad& this_ = static_cast<const EngineStartupCommanad&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL EngineStartupCommanad::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const EngineStartupCommanad& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:NUBE.EngineStartupCommanad)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 width = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_width(), target);
  }

  // uint32 height = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this_._internal_height(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NUBE.EngineStartupCommanad)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t EngineStartupCommanad::ByteSizeLong(const MessageLite& base) {
  const EngineStartupCommanad& this_ = static_cast<const EngineStartupCommanad&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t EngineStartupCommanad::ByteSizeLong() const {
  const EngineStartupCommanad& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:NUBE.EngineStartupCommanad)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // uint32 width = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_width());
    }
    // uint32 height = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_height());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void EngineStartupCommanad::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<EngineStartupCommanad*>(&to_msg);
  auto& from = static_cast<const EngineStartupCommanad&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:NUBE.EngineStartupCommanad)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_impl_.width_ = from._impl_.width_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.height_ = from._impl_.height_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void EngineStartupCommanad::CopyFrom(const EngineStartupCommanad& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:NUBE.EngineStartupCommanad)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EngineStartupCommanad::InternalSwap(EngineStartupCommanad* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(EngineStartupCommanad, _impl_.height_)
      + sizeof(EngineStartupCommanad::_impl_.height_)
      - PROTOBUF_FIELD_OFFSET(EngineStartupCommanad, _impl_.width_)>(
          reinterpret_cast<char*>(&_impl_.width_),
          reinterpret_cast<char*>(&other->_impl_.width_));
}

::google::protobuf::Metadata EngineStartupCommanad::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class KeyboardEvent::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<KeyboardEvent>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(KeyboardEvent, _impl_._has_bits_);
};

KeyboardEvent::KeyboardEvent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, KeyboardEvent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NUBE.KeyboardEvent)
}
KeyboardEvent::KeyboardEvent(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const KeyboardEvent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, KeyboardEvent_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE KeyboardEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void KeyboardEvent::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, scancode_),
           0,
           offsetof(Impl_, isdown_) -
               offsetof(Impl_, scancode_) +
               sizeof(Impl_::isdown_));
}
KeyboardEvent::~KeyboardEvent() {
  // @@protoc_insertion_point(destructor:NUBE.KeyboardEvent)
  SharedDtor(*this);
}
inline void KeyboardEvent::SharedDtor(MessageLite& self) {
  KeyboardEvent& this_ = static_cast<KeyboardEvent&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL KeyboardEvent::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) KeyboardEvent(arena);
}
constexpr auto KeyboardEvent::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(KeyboardEvent),
                                            alignof(KeyboardEvent));
}
constexpr auto KeyboardEvent::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_KeyboardEvent_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &KeyboardEvent::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<KeyboardEvent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &KeyboardEvent::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<KeyboardEvent>(), &KeyboardEvent::ByteSizeLong,
              &KeyboardEvent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(KeyboardEvent, _impl_._cached_size_),
          false,
      },
      &KeyboardEvent::kDescriptorMethods,
      &descriptor_table_nube_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull KeyboardEvent_class_data_ =
        KeyboardEvent::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
KeyboardEvent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&KeyboardEvent_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(KeyboardEvent_class_data_.tc_table);
  return KeyboardEvent_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
KeyboardEvent::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(KeyboardEvent, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    KeyboardEvent_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NUBE::KeyboardEvent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool isDown = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(KeyboardEvent, _impl_.isdown_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(KeyboardEvent, _impl_.isdown_)}},
    // uint32 scancode = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(KeyboardEvent, _impl_.scancode_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(KeyboardEvent, _impl_.scancode_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 scancode = 1;
    {PROTOBUF_FIELD_OFFSET(KeyboardEvent, _impl_.scancode_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // bool isDown = 2;
    {PROTOBUF_FIELD_OFFSET(KeyboardEvent, _impl_.isdown_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void KeyboardEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:NUBE.KeyboardEvent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    ::memset(&_impl_.scancode_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.isdown_) -
        reinterpret_cast<char*>(&_impl_.scancode_)) + sizeof(_impl_.isdown_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL KeyboardEvent::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const KeyboardEvent& this_ = static_cast<const KeyboardEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL KeyboardEvent::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const KeyboardEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:NUBE.KeyboardEvent)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 scancode = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_scancode(), target);
  }

  // bool isDown = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this_._internal_isdown(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NUBE.KeyboardEvent)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t KeyboardEvent::ByteSizeLong(const MessageLite& base) {
  const KeyboardEvent& this_ = static_cast<const KeyboardEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t KeyboardEvent::ByteSizeLong() const {
  const KeyboardEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:NUBE.KeyboardEvent)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000002U & cached_has_bits) * 2;
   {
    // uint32 scancode = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_scancode());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void KeyboardEvent::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<KeyboardEvent*>(&to_msg);
  auto& from = static_cast<const KeyboardEvent&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:NUBE.KeyboardEvent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_impl_.scancode_ = from._impl_.scancode_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.isdown_ = from._impl_.isdown_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void KeyboardEvent::CopyFrom(const KeyboardEvent& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:NUBE.KeyboardEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void KeyboardEvent::InternalSwap(KeyboardEvent* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(KeyboardEvent, _impl_.isdown_)
      + sizeof(KeyboardEvent::_impl_.isdown_)
      - PROTOBUF_FIELD_OFFSET(KeyboardEvent, _impl_.scancode_)>(
          reinterpret_cast<char*>(&_impl_.scancode_),
          reinterpret_cast<char*>(&other->_impl_.scancode_));
}

::google::protobuf::Metadata KeyboardEvent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MouseMoveEvent::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<MouseMoveEvent>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MouseMoveEvent, _impl_._has_bits_);
};

MouseMoveEvent::MouseMoveEvent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MouseMoveEvent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NUBE.MouseMoveEvent)
}
MouseMoveEvent::MouseMoveEvent(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MouseMoveEvent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MouseMoveEvent_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE MouseMoveEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void MouseMoveEvent::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, yrel_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::yrel_));
}
MouseMoveEvent::~MouseMoveEvent() {
  // @@protoc_insertion_point(destructor:NUBE.MouseMoveEvent)
  SharedDtor(*this);
}
inline void MouseMoveEvent::SharedDtor(MessageLite& self) {
  MouseMoveEvent& this_ = static_cast<MouseMoveEvent&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL MouseMoveEvent::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) MouseMoveEvent(arena);
}
constexpr auto MouseMoveEvent::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(MouseMoveEvent),
                                            alignof(MouseMoveEvent));
}
constexpr auto MouseMoveEvent::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MouseMoveEvent_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &MouseMoveEvent::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MouseMoveEvent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MouseMoveEvent::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MouseMoveEvent>(), &MouseMoveEvent::ByteSizeLong,
              &MouseMoveEvent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MouseMoveEvent, _impl_._cached_size_),
          false,
      },
      &MouseMoveEvent::kDescriptorMethods,
      &descriptor_table_nube_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull MouseMoveEvent_class_data_ =
        MouseMoveEvent::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
MouseMoveEvent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&MouseMoveEvent_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MouseMoveEvent_class_data_.tc_table);
  return MouseMoveEvent_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2>
MouseMoveEvent::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MouseMoveEvent, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    MouseMoveEvent_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NUBE::MouseMoveEvent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 yRel = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MouseMoveEvent, _impl_.yrel_), 3>(),
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(MouseMoveEvent, _impl_.yrel_)}},
    // int32 x = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MouseMoveEvent, _impl_.x_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(MouseMoveEvent, _impl_.x_)}},
    // int32 y = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MouseMoveEvent, _impl_.y_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(MouseMoveEvent, _impl_.y_)}},
    // int32 xRel = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MouseMoveEvent, _impl_.xrel_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(MouseMoveEvent, _impl_.xrel_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 x = 1;
    {PROTOBUF_FIELD_OFFSET(MouseMoveEvent, _impl_.x_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 y = 2;
    {PROTOBUF_FIELD_OFFSET(MouseMoveEvent, _impl_.y_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 xRel = 3;
    {PROTOBUF_FIELD_OFFSET(MouseMoveEvent, _impl_.xrel_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 yRel = 4;
    {PROTOBUF_FIELD_OFFSET(MouseMoveEvent, _impl_.yrel_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void MouseMoveEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:NUBE.MouseMoveEvent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    ::memset(&_impl_.x_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.yrel_) -
        reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.yrel_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL MouseMoveEvent::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const MouseMoveEvent& this_ = static_cast<const MouseMoveEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL MouseMoveEvent::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const MouseMoveEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:NUBE.MouseMoveEvent)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 x = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
            stream, this_._internal_x(), target);
  }

  // int32 y = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
            stream, this_._internal_y(), target);
  }

  // int32 xRel = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
            stream, this_._internal_xrel(), target);
  }

  // int32 yRel = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<4>(
            stream, this_._internal_yrel(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NUBE.MouseMoveEvent)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t MouseMoveEvent::ByteSizeLong(const MessageLite& base) {
  const MouseMoveEvent& this_ = static_cast<const MouseMoveEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t MouseMoveEvent::ByteSizeLong() const {
  const MouseMoveEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:NUBE.MouseMoveEvent)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // int32 x = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_x());
    }
    // int32 y = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_y());
    }
    // int32 xRel = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_xrel());
    }
    // int32 yRel = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_yrel());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void MouseMoveEvent::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<MouseMoveEvent*>(&to_msg);
  auto& from = static_cast<const MouseMoveEvent&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:NUBE.MouseMoveEvent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_impl_.x_ = from._impl_.x_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.y_ = from._impl_.y_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.xrel_ = from._impl_.xrel_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.yrel_ = from._impl_.yrel_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void MouseMoveEvent::CopyFrom(const MouseMoveEvent& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:NUBE.MouseMoveEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MouseMoveEvent::InternalSwap(MouseMoveEvent* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MouseMoveEvent, _impl_.yrel_)
      + sizeof(MouseMoveEvent::_impl_.yrel_)
      - PROTOBUF_FIELD_OFFSET(MouseMoveEvent, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::google::protobuf::Metadata MouseMoveEvent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace NUBE
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_nube_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
