// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nube.proto
// Protobuf C++ Version: 7.34.1

#ifndef nube_2eproto_2epb_2eh
#define nube_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_nube_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_nube_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_nube_2eproto;
}  // extern "C"
namespace NUBE {
class EditorEnvelope;
struct EditorEnvelopeDefaultTypeInternal;
extern EditorEnvelopeDefaultTypeInternal _EditorEnvelope_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull EditorEnvelope_class_data_;
class EngineStartupCommanad;
struct EngineStartupCommanadDefaultTypeInternal;
extern EngineStartupCommanadDefaultTypeInternal _EngineStartupCommanad_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull EngineStartupCommanad_class_data_;
class KeyboardEvent;
struct KeyboardEventDefaultTypeInternal;
extern KeyboardEventDefaultTypeInternal _KeyboardEvent_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull KeyboardEvent_class_data_;
class MouseMoveEvent;
struct MouseMoveEventDefaultTypeInternal;
extern MouseMoveEventDefaultTypeInternal _MouseMoveEvent_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull MouseMoveEvent_class_data_;
}  // namespace NUBE
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace NUBE {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED MouseMoveEvent final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:NUBE.MouseMoveEvent) */ {
 public:
  inline MouseMoveEvent() : MouseMoveEvent(nullptr) {}
  ~MouseMoveEvent() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MouseMoveEvent* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MouseMoveEvent));
  }
#endif

  template <typename = void>
  explicit constexpr MouseMoveEvent(::google::protobuf::internal::ConstantInitialized);

  inline MouseMoveEvent(const MouseMoveEvent& from) : MouseMoveEvent(nullptr, from) {}
  inline MouseMoveEvent(MouseMoveEvent&& from) noexcept
      : MouseMoveEvent(nullptr, ::std::move(from)) {}
  inline MouseMoveEvent& operator=(const MouseMoveEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline MouseMoveEvent& operator=(MouseMoveEvent&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const MouseMoveEvent& default_instance() {
    return *reinterpret_cast<const MouseMoveEvent*>(
        &_MouseMoveEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(MouseMoveEvent& a, MouseMoveEvent& b) { a.Swap(&b); }
  inline void Swap(MouseMoveEvent* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MouseMoveEvent* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] MouseMoveEvent* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MouseMoveEvent>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MouseMoveEvent& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MouseMoveEvent& from) { MouseMoveEvent::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MouseMoveEvent* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "NUBE.MouseMoveEvent"; }

  explicit MouseMoveEvent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MouseMoveEvent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MouseMoveEvent& from);
  MouseMoveEvent(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MouseMoveEvent&& from) noexcept
      : MouseMoveEvent(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kXRelFieldNumber = 3,
    kYRelFieldNumber = 4,
  };
  // int32 x = 1;
  [[nodiscard]] bool has_x()
      const;
  void clear_x() ;
  [[nodiscard]] ::int32_t x() const;
  void set_x(::int32_t value);

  private:
  ::int32_t _internal_x() const;
  void _internal_set_x(::int32_t value);

  public:
  // int32 y = 2;
  [[nodiscard]] bool has_y()
      const;
  void clear_y() ;
  [[nodiscard]] ::int32_t y() const;
  void set_y(::int32_t value);

  private:
  ::int32_t _internal_y() const;
  void _internal_set_y(::int32_t value);

  public:
  // int32 xRel = 3;
  [[nodiscard]] bool has_xrel()
      const;
  void clear_xrel() ;
  [[nodiscard]] ::int32_t xrel() const;
  void set_xrel(::int32_t value);

  private:
  ::int32_t _internal_xrel() const;
  void _internal_set_xrel(::int32_t value);

  public:
  // int32 yRel = 4;
  [[nodiscard]] bool has_yrel()
      const;
  void clear_yrel() ;
  [[nodiscard]] ::int32_t yrel() const;
  void set_yrel(::int32_t value);

  private:
  ::int32_t _internal_yrel() const;
  void _internal_set_yrel(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:NUBE.MouseMoveEvent)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MouseMoveEvent& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t x_;
    ::int32_t y_;
    ::int32_t xrel_;
    ::int32_t yrel_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_nube_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull MouseMoveEvent_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED KeyboardEvent final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:NUBE.KeyboardEvent) */ {
 public:
  inline KeyboardEvent() : KeyboardEvent(nullptr) {}
  ~KeyboardEvent() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(KeyboardEvent* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(KeyboardEvent));
  }
#endif

  template <typename = void>
  explicit constexpr KeyboardEvent(::google::protobuf::internal::ConstantInitialized);

  inline KeyboardEvent(const KeyboardEvent& from) : KeyboardEvent(nullptr, from) {}
  inline KeyboardEvent(KeyboardEvent&& from) noexcept
      : KeyboardEvent(nullptr, ::std::move(from)) {}
  inline KeyboardEvent& operator=(const KeyboardEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline KeyboardEvent& operator=(KeyboardEvent&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const KeyboardEvent& default_instance() {
    return *reinterpret_cast<const KeyboardEvent*>(
        &_KeyboardEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(KeyboardEvent& a, KeyboardEvent& b) { a.Swap(&b); }
  inline void Swap(KeyboardEvent* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(KeyboardEvent* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] KeyboardEvent* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<KeyboardEvent>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const KeyboardEvent& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const KeyboardEvent& from) { KeyboardEvent::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(KeyboardEvent* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "NUBE.KeyboardEvent"; }

  explicit KeyboardEvent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  KeyboardEvent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const KeyboardEvent& from);
  KeyboardEvent(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, KeyboardEvent&& from) noexcept
      : KeyboardEvent(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kScancodeFieldNumber = 1,
    kIsDownFieldNumber = 2,
  };
  // uint32 scancode = 1;
  [[nodiscard]] bool has_scancode()
      const;
  void clear_scancode() ;
  [[nodiscard]] ::uint32_t scancode() const;
  void set_scancode(::uint32_t value);

  private:
  ::uint32_t _internal_scancode() const;
  void _internal_set_scancode(::uint32_t value);

  public:
  // bool isDown = 2;
  [[nodiscard]] bool has_isdown()
      const;
  void clear_isdown() ;
  [[nodiscard]] bool isdown() const;
  void set_isdown(bool value);

  private:
  bool _internal_isdown() const;
  void _internal_set_isdown(bool value);

  public:
  // @@protoc_insertion_point(class_scope:NUBE.KeyboardEvent)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const KeyboardEvent& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t scancode_;
    bool isdown_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_nube_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull KeyboardEvent_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED EngineStartupCommanad final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:NUBE.EngineStartupCommanad) */ {
 public:
  inline EngineStartupCommanad() : EngineStartupCommanad(nullptr) {}
  ~EngineStartupCommanad() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EngineStartupCommanad* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EngineStartupCommanad));
  }
#endif

  template <typename = void>
  explicit constexpr EngineStartupCommanad(::google::protobuf::internal::ConstantInitialized);

  inline EngineStartupCommanad(const EngineStartupCommanad& from) : EngineStartupCommanad(nullptr, from) {}
  inline EngineStartupCommanad(EngineStartupCommanad&& from) noexcept
      : EngineStartupCommanad(nullptr, ::std::move(from)) {}
  inline EngineStartupCommanad& operator=(const EngineStartupCommanad& from) {
    CopyFrom(from);
    return *this;
  }
  inline EngineStartupCommanad& operator=(EngineStartupCommanad&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const EngineStartupCommanad& default_instance() {
    return *reinterpret_cast<const EngineStartupCommanad*>(
        &_EngineStartupCommanad_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(EngineStartupCommanad& a, EngineStartupCommanad& b) { a.Swap(&b); }
  inline void Swap(EngineStartupCommanad* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EngineStartupCommanad* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] EngineStartupCommanad* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<EngineStartupCommanad>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EngineStartupCommanad& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EngineStartupCommanad& from) { EngineStartupCommanad::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(EngineStartupCommanad* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "NUBE.EngineStartupCommanad"; }

  explicit EngineStartupCommanad(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  EngineStartupCommanad(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const EngineStartupCommanad& from);
  EngineStartupCommanad(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, EngineStartupCommanad&& from) noexcept
      : EngineStartupCommanad(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kWidthFieldNumber = 1,
    kHeightFieldNumber = 2,
  };
  // uint32 width = 1;
  [[nodiscard]] bool has_width()
      const;
  void clear_width() ;
  [[nodiscard]] ::uint32_t width() const;
  void set_width(::uint32_t value);

  private:
  ::uint32_t _internal_width() const;
  void _internal_set_width(::uint32_t value);

  public:
  // uint32 height = 2;
  [[nodiscard]] bool has_height()
      const;
  void clear_height() ;
  [[nodiscard]] ::uint32_t height() const;
  void set_height(::uint32_t value);

  private:
  ::uint32_t _internal_height() const;
  void _internal_set_height(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:NUBE.EngineStartupCommanad)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const EngineStartupCommanad& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t width_;
    ::uint32_t height_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_nube_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull EngineStartupCommanad_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED EditorEnvelope final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:NUBE.EditorEnvelope) */ {
 public:
  inline EditorEnvelope() : EditorEnvelope(nullptr) {}
  ~EditorEnvelope() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EditorEnvelope* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EditorEnvelope));
  }
#endif

  template <typename = void>
  explicit constexpr EditorEnvelope(::google::protobuf::internal::ConstantInitialized);

  inline EditorEnvelope(const EditorEnvelope& from) : EditorEnvelope(nullptr, from) {}
  inline EditorEnvelope(EditorEnvelope&& from) noexcept
      : EditorEnvelope(nullptr, ::std::move(from)) {}
  inline EditorEnvelope& operator=(const EditorEnvelope& from) {
    CopyFrom(from);
    return *this;
  }
  inline EditorEnvelope& operator=(EditorEnvelope&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const EditorEnvelope& default_instance() {
    return *reinterpret_cast<const EditorEnvelope*>(
        &_EditorEnvelope_default_instance_);
  }
  enum PayloadCase {
    kStartup = 1,
    kKeyboardEvent = 2,
    kMouseMoveEvent = 3,
    PAYLOAD_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(EditorEnvelope& a, EditorEnvelope& b) { a.Swap(&b); }
  inline void Swap(EditorEnvelope* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EditorEnvelope* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] EditorEnvelope* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<EditorEnvelope>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EditorEnvelope& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EditorEnvelope& from) { EditorEnvelope::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(EditorEnvelope* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "NUBE.EditorEnvelope"; }

  explicit EditorEnvelope(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  EditorEnvelope(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const EditorEnvelope& from);
  EditorEnvelope(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, EditorEnvelope&& from) noexcept
      : EditorEnvelope(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStartupFieldNumber = 1,
    kKeyboardEventFieldNumber = 2,
    kMouseMoveEventFieldNumber = 3,
  };
  // .NUBE.EngineStartupCommanad startup = 1;
  [[nodiscard]] bool has_startup()
      const;
  private:
  bool _internal_has_startup() const;

  public:
  void clear_startup() ;
  [[nodiscard]] const ::NUBE::EngineStartupCommanad& startup() const;
  [[nodiscard]] ::NUBE::EngineStartupCommanad* PROTOBUF_NULLABLE release_startup();
  ::NUBE::EngineStartupCommanad* PROTOBUF_NONNULL mutable_startup();
  void set_allocated_startup(::NUBE::EngineStartupCommanad* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_startup(::NUBE::EngineStartupCommanad* PROTOBUF_NULLABLE value);
  ::NUBE::EngineStartupCommanad* PROTOBUF_NULLABLE unsafe_arena_release_startup();

  private:
  const ::NUBE::EngineStartupCommanad& _internal_startup() const;
  ::NUBE::EngineStartupCommanad* PROTOBUF_NONNULL _internal_mutable_startup();

  public:
  // .NUBE.KeyboardEvent keyboardEvent = 2;
  [[nodiscard]] bool has_keyboardevent()
      const;
  private:
  bool _internal_has_keyboardevent() const;

  public:
  void clear_keyboardevent() ;
  [[nodiscard]] const ::NUBE::KeyboardEvent& keyboardevent() const;
  [[nodiscard]] ::NUBE::KeyboardEvent* PROTOBUF_NULLABLE release_keyboardevent();
  ::NUBE::KeyboardEvent* PROTOBUF_NONNULL mutable_keyboardevent();
  void set_allocated_keyboardevent(::NUBE::KeyboardEvent* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_keyboardevent(::NUBE::KeyboardEvent* PROTOBUF_NULLABLE value);
  ::NUBE::KeyboardEvent* PROTOBUF_NULLABLE unsafe_arena_release_keyboardevent();

  private:
  const ::NUBE::KeyboardEvent& _internal_keyboardevent() const;
  ::NUBE::KeyboardEvent* PROTOBUF_NONNULL _internal_mutable_keyboardevent();

  public:
  // .NUBE.MouseMoveEvent mouseMoveEvent = 3;
  [[nodiscard]] bool has_mousemoveevent()
      const;
  private:
  bool _internal_has_mousemoveevent() const;

  public:
  void clear_mousemoveevent() ;
  [[nodiscard]] const ::NUBE::MouseMoveEvent& mousemoveevent() const;
  [[nodiscard]] ::NUBE::MouseMoveEvent* PROTOBUF_NULLABLE release_mousemoveevent();
  ::NUBE::MouseMoveEvent* PROTOBUF_NONNULL mutable_mousemoveevent();
  void set_allocated_mousemoveevent(::NUBE::MouseMoveEvent* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_mousemoveevent(::NUBE::MouseMoveEvent* PROTOBUF_NULLABLE value);
  ::NUBE::MouseMoveEvent* PROTOBUF_NULLABLE unsafe_arena_release_mousemoveevent();

  private:
  const ::NUBE::MouseMoveEvent& _internal_mousemoveevent() const;
  ::NUBE::MouseMoveEvent* PROTOBUF_NONNULL _internal_mutable_mousemoveevent();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:NUBE.EditorEnvelope)
 private:
  class _Internal;
  void set_has_startup();
  void set_has_keyboardevent();
  void set_has_mousemoveevent();
  [[nodiscard]] inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 3,
                                   3, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const EditorEnvelope& from_msg);
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE startup_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE keyboardevent_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE mousemoveevent_;
    } payload_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_nube_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull EditorEnvelope_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// EditorEnvelope

// .NUBE.EngineStartupCommanad startup = 1;
inline bool EditorEnvelope::has_startup() const {
  return payload_case() == kStartup;
}
inline bool EditorEnvelope::_internal_has_startup() const {
  return payload_case() == kStartup;
}
inline void EditorEnvelope::set_has_startup() {
  _impl_._oneof_case_[0] = kStartup;
}
inline void EditorEnvelope::clear_startup() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kStartup) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.startup_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.startup_);
    }
    clear_has_payload();
  }
}
inline ::NUBE::EngineStartupCommanad* PROTOBUF_NULLABLE EditorEnvelope::release_startup() {
  // @@protoc_insertion_point(field_release:NUBE.EditorEnvelope.startup)
  if (payload_case() == kStartup) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::NUBE::EngineStartupCommanad*>(_impl_.payload_.startup_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.startup_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::NUBE::EngineStartupCommanad& EditorEnvelope::_internal_startup() const {
  return payload_case() == kStartup ? static_cast<const ::NUBE::EngineStartupCommanad&>(*reinterpret_cast<::NUBE::EngineStartupCommanad*>(_impl_.payload_.startup_))
                     : reinterpret_cast<const ::NUBE::EngineStartupCommanad&>(::NUBE::_EngineStartupCommanad_default_instance_);
}
inline const ::NUBE::EngineStartupCommanad& EditorEnvelope::startup() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NUBE.EditorEnvelope.startup)
  return _internal_startup();
}
inline ::NUBE::EngineStartupCommanad* PROTOBUF_NULLABLE EditorEnvelope::unsafe_arena_release_startup() {
  // @@protoc_insertion_point(field_unsafe_arena_release:NUBE.EditorEnvelope.startup)
  if (payload_case() == kStartup) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::NUBE::EngineStartupCommanad*>(_impl_.payload_.startup_);
    _impl_.payload_.startup_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void EditorEnvelope::unsafe_arena_set_allocated_startup(
    ::NUBE::EngineStartupCommanad* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_startup();
    _impl_.payload_.startup_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NUBE.EditorEnvelope.startup)
}
inline ::NUBE::EngineStartupCommanad* PROTOBUF_NONNULL EditorEnvelope::_internal_mutable_startup() {
  if (payload_case() != kStartup) {
    clear_payload();
    set_has_startup();
    _impl_.payload_.startup_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::NUBE::EngineStartupCommanad>(GetArena()));
  }
  return reinterpret_cast<::NUBE::EngineStartupCommanad*>(_impl_.payload_.startup_);
}
inline ::NUBE::EngineStartupCommanad* PROTOBUF_NONNULL EditorEnvelope::mutable_startup()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::NUBE::EngineStartupCommanad* _msg = _internal_mutable_startup();
  // @@protoc_insertion_point(field_mutable:NUBE.EditorEnvelope.startup)
  return _msg;
}

// .NUBE.KeyboardEvent keyboardEvent = 2;
inline bool EditorEnvelope::has_keyboardevent() const {
  return payload_case() == kKeyboardEvent;
}
inline bool EditorEnvelope::_internal_has_keyboardevent() const {
  return payload_case() == kKeyboardEvent;
}
inline void EditorEnvelope::set_has_keyboardevent() {
  _impl_._oneof_case_[0] = kKeyboardEvent;
}
inline void EditorEnvelope::clear_keyboardevent() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kKeyboardEvent) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.keyboardevent_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.keyboardevent_);
    }
    clear_has_payload();
  }
}
inline ::NUBE::KeyboardEvent* PROTOBUF_NULLABLE EditorEnvelope::release_keyboardevent() {
  // @@protoc_insertion_point(field_release:NUBE.EditorEnvelope.keyboardEvent)
  if (payload_case() == kKeyboardEvent) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::NUBE::KeyboardEvent*>(_impl_.payload_.keyboardevent_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.keyboardevent_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::NUBE::KeyboardEvent& EditorEnvelope::_internal_keyboardevent() const {
  return payload_case() == kKeyboardEvent ? static_cast<const ::NUBE::KeyboardEvent&>(*reinterpret_cast<::NUBE::KeyboardEvent*>(_impl_.payload_.keyboardevent_))
                     : reinterpret_cast<const ::NUBE::KeyboardEvent&>(::NUBE::_KeyboardEvent_default_instance_);
}
inline const ::NUBE::KeyboardEvent& EditorEnvelope::keyboardevent() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NUBE.EditorEnvelope.keyboardEvent)
  return _internal_keyboardevent();
}
inline ::NUBE::KeyboardEvent* PROTOBUF_NULLABLE EditorEnvelope::unsafe_arena_release_keyboardevent() {
  // @@protoc_insertion_point(field_unsafe_arena_release:NUBE.EditorEnvelope.keyboardEvent)
  if (payload_case() == kKeyboardEvent) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::NUBE::KeyboardEvent*>(_impl_.payload_.keyboardevent_);
    _impl_.payload_.keyboardevent_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void EditorEnvelope::unsafe_arena_set_allocated_keyboardevent(
    ::NUBE::KeyboardEvent* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_keyboardevent();
    _impl_.payload_.keyboardevent_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NUBE.EditorEnvelope.keyboardEvent)
}
inline ::NUBE::KeyboardEvent* PROTOBUF_NONNULL EditorEnvelope::_internal_mutable_keyboardevent() {
  if (payload_case() != kKeyboardEvent) {
    clear_payload();
    set_has_keyboardevent();
    _impl_.payload_.keyboardevent_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::NUBE::KeyboardEvent>(GetArena()));
  }
  return reinterpret_cast<::NUBE::KeyboardEvent*>(_impl_.payload_.keyboardevent_);
}
inline ::NUBE::KeyboardEvent* PROTOBUF_NONNULL EditorEnvelope::mutable_keyboardevent()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::NUBE::KeyboardEvent* _msg = _internal_mutable_keyboardevent();
  // @@protoc_insertion_point(field_mutable:NUBE.EditorEnvelope.keyboardEvent)
  return _msg;
}

// .NUBE.MouseMoveEvent mouseMoveEvent = 3;
inline bool EditorEnvelope::has_mousemoveevent() const {
  return payload_case() == kMouseMoveEvent;
}
inline bool EditorEnvelope::_internal_has_mousemoveevent() const {
  return payload_case() == kMouseMoveEvent;
}
inline void EditorEnvelope::set_has_mousemoveevent() {
  _impl_._oneof_case_[0] = kMouseMoveEvent;
}
inline void EditorEnvelope::clear_mousemoveevent() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kMouseMoveEvent) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.mousemoveevent_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.mousemoveevent_);
    }
    clear_has_payload();
  }
}
inline ::NUBE::MouseMoveEvent* PROTOBUF_NULLABLE EditorEnvelope::release_mousemoveevent() {
  // @@protoc_insertion_point(field_release:NUBE.EditorEnvelope.mouseMoveEvent)
  if (payload_case() == kMouseMoveEvent) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::NUBE::MouseMoveEvent*>(_impl_.payload_.mousemoveevent_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.mousemoveevent_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::NUBE::MouseMoveEvent& EditorEnvelope::_internal_mousemoveevent() const {
  return payload_case() == kMouseMoveEvent ? static_cast<const ::NUBE::MouseMoveEvent&>(*reinterpret_cast<::NUBE::MouseMoveEvent*>(_impl_.payload_.mousemoveevent_))
                     : reinterpret_cast<const ::NUBE::MouseMoveEvent&>(::NUBE::_MouseMoveEvent_default_instance_);
}
inline const ::NUBE::MouseMoveEvent& EditorEnvelope::mousemoveevent() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NUBE.EditorEnvelope.mouseMoveEvent)
  return _internal_mousemoveevent();
}
inline ::NUBE::MouseMoveEvent* PROTOBUF_NULLABLE EditorEnvelope::unsafe_arena_release_mousemoveevent() {
  // @@protoc_insertion_point(field_unsafe_arena_release:NUBE.EditorEnvelope.mouseMoveEvent)
  if (payload_case() == kMouseMoveEvent) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::NUBE::MouseMoveEvent*>(_impl_.payload_.mousemoveevent_);
    _impl_.payload_.mousemoveevent_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void EditorEnvelope::unsafe_arena_set_allocated_mousemoveevent(
    ::NUBE::MouseMoveEvent* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_mousemoveevent();
    _impl_.payload_.mousemoveevent_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NUBE.EditorEnvelope.mouseMoveEvent)
}
inline ::NUBE::MouseMoveEvent* PROTOBUF_NONNULL EditorEnvelope::_internal_mutable_mousemoveevent() {
  if (payload_case() != kMouseMoveEvent) {
    clear_payload();
    set_has_mousemoveevent();
    _impl_.payload_.mousemoveevent_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::NUBE::MouseMoveEvent>(GetArena()));
  }
  return reinterpret_cast<::NUBE::MouseMoveEvent*>(_impl_.payload_.mousemoveevent_);
}
inline ::NUBE::MouseMoveEvent* PROTOBUF_NONNULL EditorEnvelope::mutable_mousemoveevent()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::NUBE::MouseMoveEvent* _msg = _internal_mutable_mousemoveevent();
  // @@protoc_insertion_point(field_mutable:NUBE.EditorEnvelope.mouseMoveEvent)
  return _msg;
}

inline bool EditorEnvelope::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void EditorEnvelope::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline EditorEnvelope::PayloadCase EditorEnvelope::payload_case() const {
  return EditorEnvelope::PayloadCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// EngineStartupCommanad

// uint32 width = 1;
inline bool EngineStartupCommanad::has_width() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void EngineStartupCommanad::clear_width() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t EngineStartupCommanad::width() const {
  // @@protoc_insertion_point(field_get:NUBE.EngineStartupCommanad.width)
  return _internal_width();
}
inline void EngineStartupCommanad::set_width(::uint32_t value) {
  _internal_set_width(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:NUBE.EngineStartupCommanad.width)
}
inline ::uint32_t EngineStartupCommanad::_internal_width() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.width_;
}
inline void EngineStartupCommanad::_internal_set_width(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = value;
}

// uint32 height = 2;
inline bool EngineStartupCommanad::has_height() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void EngineStartupCommanad::clear_height() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t EngineStartupCommanad::height() const {
  // @@protoc_insertion_point(field_get:NUBE.EngineStartupCommanad.height)
  return _internal_height();
}
inline void EngineStartupCommanad::set_height(::uint32_t value) {
  _internal_set_height(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:NUBE.EngineStartupCommanad.height)
}
inline ::uint32_t EngineStartupCommanad::_internal_height() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.height_;
}
inline void EngineStartupCommanad::_internal_set_height(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = value;
}

// -------------------------------------------------------------------

// KeyboardEvent

// uint32 scancode = 1;
inline bool KeyboardEvent::has_scancode() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void KeyboardEvent::clear_scancode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scancode_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t KeyboardEvent::scancode() const {
  // @@protoc_insertion_point(field_get:NUBE.KeyboardEvent.scancode)
  return _internal_scancode();
}
inline void KeyboardEvent::set_scancode(::uint32_t value) {
  _internal_set_scancode(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:NUBE.KeyboardEvent.scancode)
}
inline ::uint32_t KeyboardEvent::_internal_scancode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.scancode_;
}
inline void KeyboardEvent::_internal_set_scancode(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scancode_ = value;
}

// bool isDown = 2;
inline bool KeyboardEvent::has_isdown() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void KeyboardEvent::clear_isdown() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isdown_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline bool KeyboardEvent::isdown() const {
  // @@protoc_insertion_point(field_get:NUBE.KeyboardEvent.isDown)
  return _internal_isdown();
}
inline void KeyboardEvent::set_isdown(bool value) {
  _internal_set_isdown(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:NUBE.KeyboardEvent.isDown)
}
inline bool KeyboardEvent::_internal_isdown() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.isdown_;
}
inline void KeyboardEvent::_internal_set_isdown(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isdown_ = value;
}

// -------------------------------------------------------------------

// MouseMoveEvent

// int32 x = 1;
inline bool MouseMoveEvent::has_x() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void MouseMoveEvent::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t MouseMoveEvent::x() const {
  // @@protoc_insertion_point(field_get:NUBE.MouseMoveEvent.x)
  return _internal_x();
}
inline void MouseMoveEvent::set_x(::int32_t value) {
  _internal_set_x(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:NUBE.MouseMoveEvent.x)
}
inline ::int32_t MouseMoveEvent::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void MouseMoveEvent::_internal_set_x(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// int32 y = 2;
inline bool MouseMoveEvent::has_y() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void MouseMoveEvent::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t MouseMoveEvent::y() const {
  // @@protoc_insertion_point(field_get:NUBE.MouseMoveEvent.y)
  return _internal_y();
}
inline void MouseMoveEvent::set_y(::int32_t value) {
  _internal_set_y(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:NUBE.MouseMoveEvent.y)
}
inline ::int32_t MouseMoveEvent::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void MouseMoveEvent::_internal_set_y(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// int32 xRel = 3;
inline bool MouseMoveEvent::has_xrel() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void MouseMoveEvent::clear_xrel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.xrel_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t MouseMoveEvent::xrel() const {
  // @@protoc_insertion_point(field_get:NUBE.MouseMoveEvent.xRel)
  return _internal_xrel();
}
inline void MouseMoveEvent::set_xrel(::int32_t value) {
  _internal_set_xrel(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:NUBE.MouseMoveEvent.xRel)
}
inline ::int32_t MouseMoveEvent::_internal_xrel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.xrel_;
}
inline void MouseMoveEvent::_internal_set_xrel(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.xrel_ = value;
}

// int32 yRel = 4;
inline bool MouseMoveEvent::has_yrel() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void MouseMoveEvent::clear_yrel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.yrel_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t MouseMoveEvent::yrel() const {
  // @@protoc_insertion_point(field_get:NUBE.MouseMoveEvent.yRel)
  return _internal_yrel();
}
inline void MouseMoveEvent::set_yrel(::int32_t value) {
  _internal_set_yrel(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:NUBE.MouseMoveEvent.yRel)
}
inline ::int32_t MouseMoveEvent::_internal_yrel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.yrel_;
}
inline void MouseMoveEvent::_internal_set_yrel(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.yrel_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace NUBE


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // nube_2eproto_2epb_2eh
