// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: usd.proto
// Protobuf C++ Version: 7.34.1

#include "usd.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace NUBE {
namespace USD {

inline constexpr ObjectsChanged::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        resynced_paths_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::NUBE::USD::ObjectsChanged,
            PROTOBUF_FIELD_OFFSET(::NUBE::USD::ObjectsChanged, _impl_.resynced_paths_)>()
        }
        #else  // !PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        resynced_paths_ {}
        #endif
     {}

template <typename>
constexpr ObjectsChanged::ObjectsChanged(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ObjectsChanged_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct ObjectsChangedDefaultTypeInternal {
  constexpr ObjectsChangedDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ObjectsChangedDefaultTypeInternal() {}
  union {
    ObjectsChanged _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ObjectsChangedDefaultTypeInternal _ObjectsChanged_default_instance_;
}  // namespace USD
}  // namespace NUBE
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_usd_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_usd_2eproto = nullptr;
const ::uint32_t
    TableStruct_usd_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::NUBE::USD::ObjectsChanged, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::NUBE::USD::ObjectsChanged, _impl_.resynced_paths_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::NUBE::USD::ObjectsChanged)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::NUBE::USD::_ObjectsChanged_default_instance_._instance,
};
const char descriptor_table_protodef_usd_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\tusd.proto\022\010NUBE.USD\"(\n\016ObjectsChanged\022"
    "\026\n\016resynced_paths\030\001 \003(\t"
};
static ::absl::once_flag descriptor_table_usd_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_usd_2eproto = {
    false,
    false,
    63,
    descriptor_table_protodef_usd_2eproto,
    "usd.proto",
    &descriptor_table_usd_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_usd_2eproto::offsets,
    file_level_enum_descriptors_usd_2eproto,
    file_level_service_descriptors_usd_2eproto,
};
namespace NUBE {
namespace USD {
// ===================================================================

class ObjectsChanged::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ObjectsChanged>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ObjectsChanged, _impl_._has_bits_);
};

ObjectsChanged::ObjectsChanged(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ObjectsChanged_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NUBE.USD.ObjectsChanged)
}
PROTOBUF_NDEBUG_INLINE ObjectsChanged::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::NUBE::USD::ObjectsChanged& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        resynced_paths_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::NUBE::USD::ObjectsChanged,
            PROTOBUF_FIELD_OFFSET(::NUBE::USD::ObjectsChanged, _impl_.resynced_paths_)>()
        , from.resynced_paths_}
        #else
        resynced_paths_ { visibility, arena, from.resynced_paths_ }
        #endif
     {}

ObjectsChanged::ObjectsChanged(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ObjectsChanged& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ObjectsChanged_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ObjectsChanged* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:NUBE.USD.ObjectsChanged)
}
PROTOBUF_NDEBUG_INLINE ObjectsChanged::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        resynced_paths_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::NUBE::USD::ObjectsChanged,
            PROTOBUF_FIELD_OFFSET(::NUBE::USD::ObjectsChanged, _impl_.resynced_paths_)>()
        }
        #else
        resynced_paths_ { visibility, arena }
        #endif
     {}

inline void ObjectsChanged::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ObjectsChanged::~ObjectsChanged() {
  // @@protoc_insertion_point(destructor:NUBE.USD.ObjectsChanged)
  SharedDtor(*this);
}
inline void ObjectsChanged::SharedDtor(MessageLite& self) {
  ObjectsChanged& this_ = static_cast<ObjectsChanged&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ObjectsChanged::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ObjectsChanged(arena);
}
#ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto ObjectsChanged::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ObjectsChanged),
                                            alignof(ObjectsChanged));
}
#else  // !PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto ObjectsChanged::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ObjectsChanged, _impl_.resynced_paths_) +
          decltype(ObjectsChanged::_impl_.resynced_paths_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(ObjectsChanged), alignof(ObjectsChanged), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ObjectsChanged::PlacementNew_,
                                 sizeof(ObjectsChanged),
                                 alignof(ObjectsChanged));
  }
}
#endif
constexpr auto ObjectsChanged::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ObjectsChanged_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &ObjectsChanged::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ObjectsChanged>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ObjectsChanged::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ObjectsChanged>(), &ObjectsChanged::ByteSizeLong,
              &ObjectsChanged::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ObjectsChanged, _impl_._cached_size_),
          false,
      },
      &ObjectsChanged::kDescriptorMethods,
      &descriptor_table_usd_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ObjectsChanged_class_data_ =
        ObjectsChanged::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ObjectsChanged::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ObjectsChanged_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ObjectsChanged_class_data_.tc_table);
  return ObjectsChanged_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
ObjectsChanged::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ObjectsChanged, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ObjectsChanged_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NUBE::USD::ObjectsChanged>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string resynced_paths = 1;
    {::_pbi::TcParser::FastBR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(ObjectsChanged, _impl_.resynced_paths_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string resynced_paths = 1;
    {PROTOBUF_FIELD_OFFSET(ObjectsChanged, _impl_.resynced_paths_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kBytes | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void ObjectsChanged::Clear() {
// @@protoc_insertion_point(message_clear_start:NUBE.USD.ObjectsChanged)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.resynced_paths_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ObjectsChanged::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ObjectsChanged& this_ = static_cast<const ObjectsChanged&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ObjectsChanged::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ObjectsChanged& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:NUBE.USD.ObjectsChanged)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated string resynced_paths = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_resynced_paths_size(); i < n; ++i) {
      const auto& s = this_._internal_resynced_paths().Get(i);
      target = stream->WriteString(1, s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NUBE.USD.ObjectsChanged)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ObjectsChanged::ByteSizeLong(const MessageLite& base) {
  const ObjectsChanged& this_ = static_cast<const ObjectsChanged&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ObjectsChanged::ByteSizeLong() const {
  const ObjectsChanged& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:NUBE.USD.ObjectsChanged)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated string resynced_paths = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_resynced_paths().size());
      for (int i = 0, n = this_._internal_resynced_paths().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_resynced_paths().Get(i));
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ObjectsChanged::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ObjectsChanged*>(&to_msg);
  auto& from = static_cast<const ObjectsChanged&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:NUBE.USD.ObjectsChanged)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _this->_internal_mutable_resynced_paths()->InternalMergeFromWithArena(
        ::google::protobuf::MessageLite::internal_visibility(), arena,
        from._internal_resynced_paths());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ObjectsChanged::CopyFrom(const ObjectsChanged& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:NUBE.USD.ObjectsChanged)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ObjectsChanged::InternalSwap(ObjectsChanged* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.resynced_paths_.InternalSwap(&other->_impl_.resynced_paths_);
}

::google::protobuf::Metadata ObjectsChanged::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace USD
}  // namespace NUBE
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_usd_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
